-- ============================================================================
-- DATA CONTRACTS ON SNOWFLAKE HORIZON — 08 SEED DEMO CONTRACTS
-- ============================================================================
--
-- Seeds three end-to-end demo contracts against the existing DCA demo estate:
--
--   1. CONTRACT-SALESFORCE-ACCOUNT   RAW_DEV.SALESFORCE.ACCOUNT   (CONFIDENTIAL, ALERT)
--   2. CONTRACT-SAP-FACT-REVENUE     CURATED_DEV.SAP.FACT_REVENUE (CRITICAL, BLOCK)
--   3. CONTRACT-WORKDAY-WORKERS      RAW_DEV.WORKDAY.WORKERS      (RESTRICTED, ALERT)
--
-- Each seeds: CONTRACT + BINDING + QUALITY_RULE(s) + SLA_RULE + LINEAGE_ASSERTION(s),
-- then captures the schema fingerprint. Cross-platform lineage assertions reference
-- the Horizon Context demo (sql/17_select_star_horizon_context.sql).
--
-- NOTE: Column names in QUALITY_RULE.TARGET_COLUMN are illustrative. Adjust to
-- match your deployed schema — unmatched DMF attaches are logged and skipped, and
-- unmeasured rules simply report NO_DATA, so seeding is always safe to run.
--
-- RUN AS: DATA_ADMIN
-- ============================================================================

USE ROLE DATA_ADMIN;
USE WAREHOUSE TRANSFORM_WH;
USE SCHEMA GOVERNANCE.DATA_CONTRACTS;

-- ============================================================================
-- CONTRACT 1: SALESFORCE ACCOUNT (CONFIDENTIAL, ALERT)
-- ============================================================================
INSERT INTO CONTRACT
    (CONTRACT_ID, CONTRACT_VERSION, CONTRACT_NAME, STATUS, PRODUCER_TEAM, PRODUCER_EMAIL,
     CONSUMER_TEAMS, CONSUMER_CRITICALITY, DATA_CLASSIFICATION, COMPLIANCE_FRAMEWORKS,
     DEFAULT_ENFORCEMENT, SCHEMA_STABILITY, DESCRIPTION)
SELECT
    'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0', 'Salesforce Account Master Contract', 'ACTIVE',
    'Data Engineering', 'data-eng@company.com',
    ARRAY_CONSTRUCT('Business Intelligence', 'Analytics Engineering'), 'HIGH',
    'CONFIDENTIAL', ARRAY_CONSTRUCT('GDPR', 'CCPA'),
    'ALERT', 'STABLE',
    'Governs the Salesforce Account master ingested into RAW_DEV. Source of truth for CRM identity.';

INSERT INTO CONTRACT_BINDING
    (BINDING_ID, CONTRACT_ID, CONTRACT_VERSION, OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME,
     OBJECT_TYPE, ENFORCEMENT_MODE, DATA_LAYER)
SELECT 'BIND-SF-ACCOUNT', 'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0',
       'RAW_DEV', 'SALESFORCE', 'ACCOUNT', 'TABLE', 'ALERT', 'RAW';

INSERT INTO QUALITY_RULE
    (RULE_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID, RULE_NAME, RULE_DESCRIPTION,
     DMF_NAME, TARGET_COLUMN, COMPARATOR, THRESHOLD_VALUE, WARNING_THRESHOLD, SEVERITY)
SELECT * FROM VALUES
    ('QR-SF-ACCT-PK',    'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0', 'BIND-SF-ACCOUNT',
        'Account ID never null', 'Business key must always be populated',
        'GOVERNANCE.DATA_CONTRACTS.DMF_ORPHAN_KEY_COUNT', 'ID', '=', 0, NULL, 'ERROR'),
    ('QR-SF-ACCT-DUP',   'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0', 'BIND-SF-ACCOUNT',
        'Account ID unique', 'No duplicate account IDs among current records',
        'SNOWFLAKE.CORE.DUPLICATE_COUNT', 'ID', '<=', 0, NULL, 'ERROR'),
    ('QR-SF-ACCT-EMAIL', 'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0', 'BIND-SF-ACCOUNT',
        'Valid emails', 'Fewer than 50 invalid emails tolerated',
        'GOVERNANCE.DATA_CONTRACTS.DMF_INVALID_EMAIL_COUNT', 'EMAIL', '<=', 50, 10, 'WARN');

INSERT INTO SLA_RULE
    (SLA_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID,
     FRESHNESS_TARGET_MIN, FRESHNESS_MAX_MIN, MIN_ROW_COUNT, ON_BREACH)
SELECT 'SLA-SF-ACCOUNT', 'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0', 'BIND-SF-ACCOUNT',
       60, 360, 1, 'ALERT';

INSERT INTO LINEAGE_ASSERTION
    (ASSERTION_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID, ASSERTION_TYPE,
     RELATED_OBJECT, RELATED_PLATFORM, IS_CRITICAL, ON_BREACH)
SELECT * FROM VALUES
    ('LA-SF-DOWN', 'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0', 'BIND-SF-ACCOUNT',
        'DOWNSTREAM_EXPECTED', 'CURATED_DEV.SALESFORCE.DIM_CUSTOMER', 'Snowflake', FALSE, 'ALERT'),
    ('LA-SF-XPLAT', 'CONTRACT-SALESFORCE-ACCOUNT', '1.0.0', 'BIND-SF-ACCOUNT',
        'CROSS_PLATFORM', 'postgres.public.customers', 'PostgreSQL', FALSE, 'ALERT');

-- ============================================================================
-- CONTRACT 2: SAP FACT_REVENUE (CRITICAL, BLOCK) — the "certified" data product
-- ============================================================================
INSERT INTO CONTRACT
    (CONTRACT_ID, CONTRACT_VERSION, CONTRACT_NAME, STATUS, PRODUCER_TEAM, PRODUCER_EMAIL,
     CONSUMER_TEAMS, CONSUMER_CRITICALITY, DATA_CLASSIFICATION, COMPLIANCE_FRAMEWORKS,
     DEFAULT_ENFORCEMENT, SCHEMA_STABILITY, BREAKING_CHANGE_POLICY, DESCRIPTION)
SELECT
    'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'Revenue Fact Certified Contract', 'ACTIVE',
    'Data Engineering', 'data-eng@company.com',
    ARRAY_CONSTRUCT('Business Intelligence', 'Finance Leadership', 'Executive'), 'CRITICAL',
    'CONFIDENTIAL', ARRAY_CONSTRUCT('SOX'),
    'BLOCK', 'STABLE', 'VERSION_BUMP_REQUIRED',
    'Certified revenue fact table. Highest-consumed asset (feeds semantic view + exec dashboards). '
    || 'Breaking changes BLOCK the pipeline — consumers depend on stability.';

INSERT INTO CONTRACT_BINDING
    (BINDING_ID, CONTRACT_ID, CONTRACT_VERSION, OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME,
     OBJECT_TYPE, ENFORCEMENT_MODE, DATA_LAYER)
SELECT 'BIND-SAP-FACT-REVENUE', 'CONTRACT-SAP-FACT-REVENUE', '1.0.0',
       'CURATED_DEV', 'SAP', 'FACT_REVENUE', 'DYNAMIC TABLE', 'BLOCK', 'CURATED';

INSERT INTO QUALITY_RULE
    (RULE_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID, RULE_NAME, RULE_DESCRIPTION,
     DMF_NAME, TARGET_COLUMN, COMPARATOR, THRESHOLD_VALUE, SEVERITY)
SELECT * FROM VALUES
    ('QR-REV-NONNEG', 'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'BIND-SAP-FACT-REVENUE',
        'No negative revenue', 'Revenue amount must be >= 0',
        'GOVERNANCE.DATA_CONTRACTS.DMF_NEGATIVE_AMOUNT_COUNT', 'NET_REVENUE', '=', 0, 'ERROR'),
    ('QR-REV-NONULL', 'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'BIND-SAP-FACT-REVENUE',
        'Revenue never null', 'Net revenue must always be populated',
        'SNOWFLAKE.CORE.NULL_COUNT', 'NET_REVENUE', '=', 0, 'ERROR'),
    ('QR-REV-NOFUTURE', 'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'BIND-SAP-FACT-REVENUE',
        'No future order dates', 'Order date cannot be in the future',
        'GOVERNANCE.DATA_CONTRACTS.DMF_FUTURE_DATE_COUNT', 'ORDER_DATE', '=', 0, 'ERROR');

INSERT INTO SLA_RULE
    (SLA_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID,
     FRESHNESS_TARGET_MIN, FRESHNESS_MAX_MIN, MIN_ROW_COUNT, ROW_COUNT_DRIFT_PCT, ON_BREACH)
SELECT 'SLA-SAP-FACT-REVENUE', 'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'BIND-SAP-FACT-REVENUE',
       60, 120, 1, 25, 'BLOCK';

INSERT INTO LINEAGE_ASSERTION
    (ASSERTION_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID, ASSERTION_TYPE,
     RELATED_OBJECT, RELATED_PLATFORM, IS_CRITICAL, ON_BREACH)
SELECT * FROM VALUES
    ('LA-REV-UP',    'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'BIND-SAP-FACT-REVENUE',
        'UPSTREAM_REQUIRED', 'RAW_DEV.SAP.VBAK', 'Snowflake', TRUE, 'BLOCK'),
    ('LA-REV-SEM',   'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'BIND-SAP-FACT-REVENUE',
        'DOWNSTREAM_EXPECTED', 'SEM_DEV.SAP.REVENUE_SUMMARY', 'Snowflake', TRUE, 'ALERT'),
    ('LA-REV-TAB',   'CONTRACT-SAP-FACT-REVENUE', '1.0.0', 'BIND-SAP-FACT-REVENUE',
        'CROSS_PLATFORM', 'tableau://Executive Suite/Executive Revenue Dashboard', 'Tableau', TRUE, 'ALERT');

-- ============================================================================
-- CONTRACT 3: WORKDAY WORKERS (RESTRICTED, ALERT) — sensitive PII
-- ============================================================================
INSERT INTO CONTRACT
    (CONTRACT_ID, CONTRACT_VERSION, CONTRACT_NAME, STATUS, PRODUCER_TEAM, PRODUCER_EMAIL,
     CONSUMER_TEAMS, CONSUMER_CRITICALITY, DATA_CLASSIFICATION, COMPLIANCE_FRAMEWORKS,
     DEFAULT_ENFORCEMENT, SCHEMA_STABILITY, DESCRIPTION)
SELECT
    'CONTRACT-WORKDAY-WORKERS', '1.0.0', 'Workday Workers PII Contract', 'ACTIVE',
    'HR Analytics', 'hr-analytics@company.com',
    ARRAY_CONSTRUCT('HR Analytics', 'Finance Analytics'), 'HIGH',
    'RESTRICTED', ARRAY_CONSTRUCT('GDPR'),
    'ALERT', 'STABLE',
    'Governs Workday worker records containing NAME/EMAIL/SALARY PII. Restricted classification — '
    || 'downstream must inherit masking. Schema stability protects HR reporting.';

INSERT INTO CONTRACT_BINDING
    (BINDING_ID, CONTRACT_ID, CONTRACT_VERSION, OBJECT_DATABASE, OBJECT_SCHEMA, OBJECT_NAME,
     OBJECT_TYPE, ENFORCEMENT_MODE, DATA_LAYER)
SELECT 'BIND-WD-WORKERS', 'CONTRACT-WORKDAY-WORKERS', '1.0.0',
       'RAW_DEV', 'WORKDAY', 'WORKERS', 'TABLE', 'ALERT', 'RAW';

INSERT INTO QUALITY_RULE
    (RULE_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID, RULE_NAME, RULE_DESCRIPTION,
     DMF_NAME, TARGET_COLUMN, COMPARATOR, THRESHOLD_VALUE, SEVERITY)
SELECT * FROM VALUES
    ('QR-WD-KEY',   'CONTRACT-WORKDAY-WORKERS', '1.0.0', 'BIND-WD-WORKERS',
        'Worker ID never null', 'Worker business key must be populated',
        'GOVERNANCE.DATA_CONTRACTS.DMF_ORPHAN_KEY_COUNT', 'WORKER_ID', '=', 0, 'ERROR'),
    ('QR-WD-SALARY', 'CONTRACT-WORKDAY-WORKERS', '1.0.0', 'BIND-WD-WORKERS',
        'No negative salary', 'Compensation must be non-negative',
        'GOVERNANCE.DATA_CONTRACTS.DMF_NEGATIVE_AMOUNT_COUNT', 'COMPENSATION', '=', 0, 'ERROR');

INSERT INTO SLA_RULE
    (SLA_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID,
     FRESHNESS_TARGET_MIN, FRESHNESS_MAX_MIN, MIN_ROW_COUNT, ON_BREACH)
SELECT 'SLA-WD-WORKERS', 'CONTRACT-WORKDAY-WORKERS', '1.0.0', 'BIND-WD-WORKERS',
       240, 1440, 1, 'ALERT';

INSERT INTO LINEAGE_ASSERTION
    (ASSERTION_ID, CONTRACT_ID, CONTRACT_VERSION, BINDING_ID, ASSERTION_TYPE,
     RELATED_OBJECT, RELATED_PLATFORM, IS_CRITICAL, ON_BREACH)
SELECT 'LA-WD-XPLAT', 'CONTRACT-WORKDAY-WORKERS', '1.0.0', 'BIND-WD-WORKERS',
       'CROSS_PLATFORM', 'SEM_DEV.WORKDAY.WORKFORCE_SUMMARY', 'Snowflake', FALSE, 'ALERT';

-- ============================================================================
-- APPLY: capture schema fingerprints + tag objects + attach DMFs
-- ============================================================================

-- Schema fingerprints (safe if the object exists; errors are surfaced in output)
CALL CAPTURE_SCHEMA_FINGERPRINT('BIND-SF-ACCOUNT');
CALL CAPTURE_SCHEMA_FINGERPRINT('BIND-SAP-FACT-REVENUE');
CALL CAPTURE_SCHEMA_FINGERPRINT('BIND-WD-WORKERS');

-- Bind objects to contracts via Horizon tags (survives renames, queryable in TAG_REFERENCES)
-- Wrapped individually; comment out any line whose object is not deployed.
ALTER TABLE RAW_DEV.SALESFORCE.ACCOUNT
    SET TAG GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_ID = 'CONTRACT-SALESFORCE-ACCOUNT',
            GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_VERSION = '1.0.0',
            GOVERNANCE.DATA_CONTRACTS.TAG_SCHEMA_STABILITY = 'STABLE',
            GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_ENFORCEMENT = 'ALERT';

ALTER TABLE CURATED_DEV.SAP.FACT_REVENUE
    SET TAG GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_ID = 'CONTRACT-SAP-FACT-REVENUE',
            GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_VERSION = '1.0.0',
            GOVERNANCE.DATA_CONTRACTS.TAG_SCHEMA_STABILITY = 'STABLE',
            GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_ENFORCEMENT = 'BLOCK';

ALTER TABLE RAW_DEV.WORKDAY.WORKERS
    SET TAG GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_ID = 'CONTRACT-WORKDAY-WORKERS',
            GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_VERSION = '1.0.0',
            GOVERNANCE.DATA_CONTRACTS.TAG_SCHEMA_STABILITY = 'STABLE',
            GOVERNANCE.DATA_CONTRACTS.TAG_CONTRACT_ENFORCEMENT = 'ALERT';

-- Attach quality DMFs on a schedule (TRIGGER_ON_CHANGES = evaluate on data change)
CALL APPLY_QUALITY_RULES('CONTRACT-SALESFORCE-ACCOUNT', 'TRIGGER_ON_CHANGES');
CALL APPLY_QUALITY_RULES('CONTRACT-SAP-FACT-REVENUE',   'TRIGGER_ON_CHANGES');
CALL APPLY_QUALITY_RULES('CONTRACT-WORKDAY-WORKERS',    'TRIGGER_ON_CHANGES');

SELECT '✓ Seeded 3 demo contracts with bindings, quality/SLA/lineage rules, fingerprints, and tags' AS STATUS;
SELECT '  Run a validation:  CALL GOVERNANCE.DATA_CONTRACTS.VALIDATE_CONTRACT(''CONTRACT-SAP-FACT-REVENUE'', ''_LOADED_AT'', ''MANUAL'');' AS NEXT_STEP;
