-- ============================================================================
-- 06b_stage_semantic_models.sql — stage the generated Cortex Analyst models
-- ----------------------------------------------------------------------------
-- Uploads every per-source analytics model YAML (generated by
-- tools/generate_semantic_models.py) to the CONFIG.CORTEX_ANALYST_MODELS stage
-- so a Cortex Analyst / Agent can point at the right model per source system.
-- These files appear in the Cortex Analyst model picker as analytics_<source>.yaml.
--
--     cd demo
--     python tools/generate_semantic_models.py     # writes analytics_models/*.yaml
--     snow sql -f 06b_stage_semantic_models.sql
--
-- Run AFTER 06_gold_views.sql (the YAMLs reference GOLD.V_<SYSTEM>_* views).
-- ============================================================================

USE ROLE      ONT_DEMO_BUILDER_ROLE;
USE DATABASE  ONT_DEMO;
USE SCHEMA    CONFIG;
USE WAREHOUSE ONT_DEMO_INGEST_WH;

-- The CONFIG.CORTEX_ANALYST_MODELS stage is created by 01_setup_database.sql; the
-- builder role has READ/WRITE on it (PUT only needs WRITE).
-- `snow sql` resolves the relative file:// path against the current directory.
-- Files land at the stage root (LS echoes the stage name as a path prefix).
PUT file://analytics_models/*.yaml
    @ONT_DEMO.CONFIG.CORTEX_ANALYST_MODELS/
    OVERWRITE = TRUE AUTO_COMPRESS = FALSE;

LS @ONT_DEMO.CONFIG.CORTEX_ANALYST_MODELS/;

SELECT 'Per-source analytics models staged to @ONT_DEMO.CONFIG.CORTEX_ANALYST_MODELS/.' AS status;
