-- Teardown for the ontology demo.
USE ROLE ACCOUNTADMIN;

-- Demo users created by 09_governance_policies.sql (one per source system)
DROP USER      IF EXISTS SAP_ANALYST;
DROP USER      IF EXISTS SALESFORCE_ANALYST;
DROP USER      IF EXISTS ORACLE_ANALYST;
DROP USER      IF EXISTS FHIR_ANALYST;
DROP USER      IF EXISTS WORKDAY_ANALYST;
DROP USER      IF EXISTS SERVICENOW_ANALYST;
DROP USER      IF EXISTS CISO_DEMO;

DROP DATABASE  IF EXISTS ONT_DEMO;
DROP WAREHOUSE IF EXISTS ONT_DEMO_INGEST_WH;
DROP WAREHOUSE IF EXISTS ONT_DEMO_SEARCH_WH;
DROP WAREHOUSE IF EXISTS ONT_DEMO_AGENT_WH;
DROP WAREHOUSE IF EXISTS ONT_DEMO_ANALYTICS_WH;
DROP ROLE      IF EXISTS ONT_DEMO_BUILDER_ROLE;
DROP ROLE      IF EXISTS ONT_DEMO_CONSUMER_ROLE;

SELECT 'ONT_DEMO removed.' AS status;
