-- ============================================================================
-- DATA LOADING - Load Synthetic Data into RAW Layer
-- ============================================================================
-- 
-- This script loads synthetic data from the staging area into RAW tables.
-- Supports two modes:
--   1. Load from CSV files (generated by Python data_generator.py)
--   2. Generate simple data in-Snowflake (for quick demos)
--
-- RUN AS: DATA_ADMIN
-- ============================================================================

USE ROLE DATA_ADMIN;
USE WAREHOUSE INGEST_WH;
USE DATABASE RAW_DEV;

-- ═══════════════════════════════════════════════════════════════════════════
-- OPTION A: LOAD FROM CSV FILES
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- Prerequisites:
--   1. Generate data: python tools/data_generator.py --output data
--   2. Upload to stage:
--      PUT file://data/customers.csv @RAW_DEV.STAGING.DATA_STAGE AUTO_COMPRESS=TRUE;
--      PUT file://data/products.csv @RAW_DEV.STAGING.DATA_STAGE AUTO_COMPRESS=TRUE;
--      PUT file://data/orders.csv @RAW_DEV.STAGING.DATA_STAGE AUTO_COMPRESS=TRUE;
--      PUT file://data/employees.csv @RAW_DEV.STAGING.DATA_STAGE AUTO_COMPRESS=TRUE;
--      PUT file://data/departments.csv @RAW_DEV.STAGING.DATA_STAGE AUTO_COMPRESS=TRUE;
--
-- ═══════════════════════════════════════════════════════════════════════════

-- List files in stage
-- LIST @RAW_DEV.STAGING.DATA_STAGE;

-- Load customers
/*
COPY INTO RAW_DEV.CRM.CUSTOMER_RAW
FROM @RAW_DEV.STAGING.DATA_STAGE/customers
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = 'CONTINUE'
PURGE = FALSE;
*/

-- Load products
/*
COPY INTO RAW_DEV.CRM.PRODUCT_RAW
FROM @RAW_DEV.STAGING.DATA_STAGE/products
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = 'CONTINUE'
PURGE = FALSE;
*/

-- Load orders
/*
COPY INTO RAW_DEV.CRM.ORDER_RAW
FROM @RAW_DEV.STAGING.DATA_STAGE/orders
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = 'CONTINUE'
PURGE = FALSE;
*/

-- Load employees
/*
COPY INTO RAW_DEV.HR.EMPLOYEE_RAW
FROM @RAW_DEV.STAGING.DATA_STAGE/employees
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = 'CONTINUE'
PURGE = FALSE;
*/

-- ═══════════════════════════════════════════════════════════════════════════
-- OPTION B: GENERATE SIMPLE DATA IN-SNOWFLAKE
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- For quick demos, generate simplified data directly in Snowflake.
-- Less diverse than Python generator but quick to set up.
--
-- ═══════════════════════════════════════════════════════════════════════════

-- Generate sample customers
INSERT INTO RAW_DEV.CRM.CUSTOMER_RAW (
    CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE,
    ADDRESS_LINE1, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY,
    COMPANY_NAME, INDUSTRY, CUSTOMER_TYPE, CUSTOMER_STATUS, CUSTOMER_SEGMENT,
    LIFETIME_VALUE, CREDIT_LIMIT, CURRENCY_CODE,
    CREATED_DATE, REGION, MARKETING_CONSENT, DATA_PROCESSING_CONSENT,
    _ROW_HASH, _IS_CURRENT, _VALID_FROM, _VALID_TO
)
SELECT 
    'CUST-' || LPAD(SEQ4()::STRING, 8, '0') AS CUSTOMER_ID,
    ARRAY_CONSTRUCT('James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda', 'William', 'Elizabeth')[UNIFORM(0, 9, RANDOM())] AS FIRST_NAME,
    ARRAY_CONSTRUCT('Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez')[UNIFORM(0, 9, RANDOM())] AS LAST_NAME,
    LOWER(FIRST_NAME) || '.' || LOWER(LAST_NAME) || SEQ4() || '@example.com' AS EMAIL,
    '+1-' || UNIFORM(200, 999, RANDOM()) || '-' || UNIFORM(200, 999, RANDOM()) || '-' || UNIFORM(1000, 9999, RANDOM()) AS PHONE,
    UNIFORM(100, 9999, RANDOM()) || ' ' || ARRAY_CONSTRUCT('Main', 'Oak', 'Maple', 'Cedar', 'Pine')[UNIFORM(0, 4, RANDOM())] || ' Street' AS ADDRESS_LINE1,
    ARRAY_CONSTRUCT('New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose')[UNIFORM(0, 9, RANDOM())] AS CITY,
    ARRAY_CONSTRUCT('NY', 'CA', 'IL', 'TX', 'AZ', 'PA', 'TX', 'CA', 'TX', 'CA')[UNIFORM(0, 9, RANDOM())] AS STATE_PROVINCE,
    LPAD(UNIFORM(10000, 99999, RANDOM())::STRING, 5, '0') AS POSTAL_CODE,
    'United States' AS COUNTRY,
    CASE WHEN UNIFORM(0, 100, RANDOM()) > 30 THEN 'Company ' || SEQ4() || ' Inc.' ELSE NULL END AS COMPANY_NAME,
    ARRAY_CONSTRUCT('Technology', 'Healthcare', 'Finance', 'Retail', 'Manufacturing')[UNIFORM(0, 4, RANDOM())] AS INDUSTRY,
    CASE WHEN COMPANY_NAME IS NOT NULL THEN 'Business' ELSE 'Individual' END AS CUSTOMER_TYPE,
    ARRAY_CONSTRUCT('Active', 'Active', 'Active', 'Active', 'Inactive', 'Prospect')[UNIFORM(0, 5, RANDOM())] AS CUSTOMER_STATUS,
    ARRAY_CONSTRUCT('Enterprise', 'Mid-Market', 'SMB', 'Startup', 'Consumer')[UNIFORM(0, 4, RANDOM())] AS CUSTOMER_SEGMENT,
    ROUND(UNIFORM(100, 100000, RANDOM())::FLOAT, 2) AS LIFETIME_VALUE,
    ROUND(UNIFORM(1000, 50000, RANDOM())::FLOAT, 2) AS CREDIT_LIMIT,
    'USD' AS CURRENCY_CODE,
    DATEADD(DAY, -UNIFORM(1, 1825, RANDOM()), CURRENT_DATE()) AS CREATED_DATE,
    ARRAY_CONSTRUCT('North America', 'EMEA', 'APAC', 'LATAM')[UNIFORM(0, 3, RANDOM())] AS REGION,
    UNIFORM(0, 100, RANDOM()) > 30 AS MARKETING_CONSENT,
    TRUE AS DATA_PROCESSING_CONSENT,
    SHA2(SEQ4()::STRING, 256) AS _ROW_HASH,
    TRUE AS _IS_CURRENT,
    CURRENT_TIMESTAMP() AS _VALID_FROM,
    '9999-12-31'::TIMESTAMP_NTZ AS _VALID_TO
FROM TABLE(GENERATOR(ROWCOUNT => 5000));

-- Generate sample products
INSERT INTO RAW_DEV.CRM.PRODUCT_RAW (
    PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_DESCRIPTION,
    PRODUCT_CATEGORY, PRODUCT_SUBCATEGORY, PRODUCT_LINE, BRAND,
    LIST_PRICE, COST_PRICE, CURRENCY_CODE,
    PRODUCT_STATUS, IS_ACTIVE, LAUNCH_DATE,
    _ROW_HASH, _IS_CURRENT, _VALID_FROM, _VALID_TO
)
SELECT
    'PROD-' || LPAD(SEQ4()::STRING, 6, '0') AS PRODUCT_ID,
    UPPER(LEFT(PRODUCT_CATEGORY, 3)) || '-' || LPAD(SEQ4()::STRING, 4, '0') AS PRODUCT_CODE,
    ARRAY_CONSTRUCT('Pro', 'Elite', 'Basic', 'Premium', 'Standard')[UNIFORM(0, 4, RANDOM())] || ' ' ||
    ARRAY_CONSTRUCT('Widget', 'Gadget', 'Solution', 'Platform', 'Service')[UNIFORM(0, 4, RANDOM())] || ' ' ||
    ARRAY_CONSTRUCT('X1', 'Plus', '2.0', 'Enterprise', 'Cloud')[UNIFORM(0, 4, RANDOM())] AS PRODUCT_NAME,
    'High-quality product for enterprise needs.' AS PRODUCT_DESCRIPTION,
    ARRAY_CONSTRUCT('Software', 'Hardware', 'Services', 'Subscriptions')[UNIFORM(0, 3, RANDOM())] AS PRODUCT_CATEGORY,
    ARRAY_CONSTRUCT('SaaS', 'On-Premise', 'Consulting', 'Support')[UNIFORM(0, 3, RANDOM())] AS PRODUCT_SUBCATEGORY,
    PRODUCT_CATEGORY || ' Solutions' AS PRODUCT_LINE,
    ARRAY_CONSTRUCT('TechCorp', 'DataFlow', 'CloudFirst', 'InnovateTech')[UNIFORM(0, 3, RANDOM())] AS BRAND,
    ROUND(UNIFORM(99, 9999, RANDOM())::FLOAT, 2) AS LIST_PRICE,
    ROUND(LIST_PRICE * UNIFORM(30, 70, RANDOM()) / 100, 2) AS COST_PRICE,
    'USD' AS CURRENCY_CODE,
    'Active' AS PRODUCT_STATUS,
    TRUE AS IS_ACTIVE,
    DATEADD(DAY, -UNIFORM(1, 1095, RANDOM()), CURRENT_DATE()) AS LAUNCH_DATE,
    SHA2(SEQ4()::STRING, 256) AS _ROW_HASH,
    TRUE AS _IS_CURRENT,
    CURRENT_TIMESTAMP() AS _VALID_FROM,
    '9999-12-31'::TIMESTAMP_NTZ AS _VALID_TO
FROM TABLE(GENERATOR(ROWCOUNT => 200));

-- Generate sample orders
INSERT INTO RAW_DEV.CRM.ORDER_RAW (
    ORDER_ID, ORDER_NUMBER, CUSTOMER_ID, SALES_REP_ID,
    ORDER_DATE, ORDER_STATUS, ORDER_TYPE, ORDER_PRIORITY,
    SUBTOTAL, DISCOUNT_AMOUNT, TAX_AMOUNT, SHIPPING_AMOUNT, ORDER_TOTAL,
    CURRENCY_CODE, SALES_CHANNEL, REGION,
    _ROW_HASH, _IS_CURRENT, _VALID_FROM, _VALID_TO
)
SELECT
    'ORD-' || LPAD(SEQ4()::STRING, 10, '0') AS ORDER_ID,
    'SO-' || YEAR(ORDER_DATE) || '-' || LPAD(SEQ4()::STRING, 8, '0') AS ORDER_NUMBER,
    'CUST-' || LPAD(UNIFORM(1, 5000, RANDOM())::STRING, 8, '0') AS CUSTOMER_ID,
    'EMP-' || LPAD(UNIFORM(1, 200, RANDOM())::STRING, 6, '0') AS SALES_REP_ID,
    DATEADD(DAY, -UNIFORM(1, 730, RANDOM()), CURRENT_DATE()) AS ORDER_DATE,
    ARRAY_CONSTRUCT('Pending', 'Processing', 'Shipped', 'Delivered', 'Delivered', 'Delivered')[UNIFORM(0, 5, RANDOM())] AS ORDER_STATUS,
    ARRAY_CONSTRUCT('New', 'Renewal', 'Upsell')[UNIFORM(0, 2, RANDOM())] AS ORDER_TYPE,
    ARRAY_CONSTRUCT('Low', 'Medium', 'High')[UNIFORM(0, 2, RANDOM())] AS ORDER_PRIORITY,
    ROUND(UNIFORM(100, 5000, RANDOM())::FLOAT, 2) AS SUBTOTAL,
    ROUND(SUBTOTAL * UNIFORM(0, 20, RANDOM()) / 100, 2) AS DISCOUNT_AMOUNT,
    ROUND((SUBTOTAL - DISCOUNT_AMOUNT) * 0.08, 2) AS TAX_AMOUNT,
    ROUND(UNIFORM(0, 50, RANDOM())::FLOAT, 2) AS SHIPPING_AMOUNT,
    ROUND(SUBTOTAL - DISCOUNT_AMOUNT + TAX_AMOUNT + SHIPPING_AMOUNT, 2) AS ORDER_TOTAL,
    'USD' AS CURRENCY_CODE,
    ARRAY_CONSTRUCT('Direct', 'Partner', 'Online', 'Field Sales')[UNIFORM(0, 3, RANDOM())] AS SALES_CHANNEL,
    ARRAY_CONSTRUCT('North America', 'EMEA', 'APAC', 'LATAM')[UNIFORM(0, 3, RANDOM())] AS REGION,
    SHA2(SEQ4()::STRING, 256) AS _ROW_HASH,
    TRUE AS _IS_CURRENT,
    CURRENT_TIMESTAMP() AS _VALID_FROM,
    '9999-12-31'::TIMESTAMP_NTZ AS _VALID_TO
FROM TABLE(GENERATOR(ROWCOUNT => 20000));

-- Generate sample employees
INSERT INTO RAW_DEV.HR.EMPLOYEE_RAW (
    EMPLOYEE_ID, EMPLOYEE_NUMBER, FIRST_NAME, LAST_NAME, EMAIL,
    PHONE_WORK, SSN, DATE_OF_BIRTH, GENDER,
    HOME_CITY, HOME_STATE, HOME_COUNTRY,
    HIRE_DATE, EMPLOYMENT_STATUS, EMPLOYMENT_TYPE,
    JOB_TITLE, JOB_LEVEL, DEPARTMENT_NAME, DIVISION,
    WORK_LOCATION, WORK_COUNTRY, REMOTE_WORKER,
    BASE_SALARY, SALARY_CURRENCY,
    _ROW_HASH, _IS_CURRENT, _VALID_FROM, _VALID_TO
)
SELECT
    'EMP-' || LPAD(SEQ4()::STRING, 6, '0') AS EMPLOYEE_ID,
    'E' || LPAD(SEQ4()::STRING, 6, '0') AS EMPLOYEE_NUMBER,
    ARRAY_CONSTRUCT('James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda', 'William', 'Elizabeth')[UNIFORM(0, 9, RANDOM())] AS FIRST_NAME,
    ARRAY_CONSTRUCT('Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez')[UNIFORM(0, 9, RANDOM())] AS LAST_NAME,
    LOWER(FIRST_NAME) || '.' || LOWER(LAST_NAME) || '@company.com' AS EMAIL,
    '+1-' || UNIFORM(200, 999, RANDOM()) || '-' || UNIFORM(200, 999, RANDOM()) || '-' || UNIFORM(1000, 9999, RANDOM()) AS PHONE_WORK,
    UNIFORM(100, 999, RANDOM()) || '-' || UNIFORM(10, 99, RANDOM()) || '-' || UNIFORM(1000, 9999, RANDOM()) AS SSN,
    DATEADD(YEAR, -UNIFORM(22, 65, RANDOM()), CURRENT_DATE()) AS DATE_OF_BIRTH,
    ARRAY_CONSTRUCT('Male', 'Female', 'Non-binary')[UNIFORM(0, 2, RANDOM())] AS GENDER,
    ARRAY_CONSTRUCT('New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix')[UNIFORM(0, 4, RANDOM())] AS HOME_CITY,
    ARRAY_CONSTRUCT('NY', 'CA', 'IL', 'TX', 'AZ')[UNIFORM(0, 4, RANDOM())] AS HOME_STATE,
    'United States' AS HOME_COUNTRY,
    DATEADD(DAY, -UNIFORM(1, 5475, RANDOM()), CURRENT_DATE()) AS HIRE_DATE,
    'Active' AS EMPLOYMENT_STATUS,
    'Full-Time' AS EMPLOYMENT_TYPE,
    ARRAY_CONSTRUCT('Manager', 'Senior', 'Lead', 'Analyst', 'Specialist')[UNIFORM(0, 4, RANDOM())] || ' ' ||
    ARRAY_CONSTRUCT('Engineer', 'Analyst', 'Coordinator', 'Associate')[UNIFORM(0, 3, RANDOM())] AS JOB_TITLE,
    ARRAY_CONSTRUCT('Individual Contributor', 'Senior', 'Lead', 'Manager', 'Director')[UNIFORM(0, 4, RANDOM())] AS JOB_LEVEL,
    ARRAY_CONSTRUCT('Engineering', 'Sales', 'Marketing', 'Finance', 'HR', 'Operations')[UNIFORM(0, 5, RANDOM())] AS DEPARTMENT_NAME,
    'Corporate' AS DIVISION,
    HOME_CITY || ' Office' AS WORK_LOCATION,
    'United States' AS WORK_COUNTRY,
    UNIFORM(0, 100, RANDOM()) > 60 AS REMOTE_WORKER,
    ROUND(UNIFORM(50000, 200000, RANDOM())::FLOAT, 2) AS BASE_SALARY,
    'USD' AS SALARY_CURRENCY,
    SHA2(SEQ4()::STRING, 256) AS _ROW_HASH,
    TRUE AS _IS_CURRENT,
    CURRENT_TIMESTAMP() AS _VALID_FROM,
    '9999-12-31'::TIMESTAMP_NTZ AS _VALID_TO
FROM TABLE(GENERATOR(ROWCOUNT => 500));

-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFICATION
-- ═══════════════════════════════════════════════════════════════════════════

SELECT '✓ Data Loading Complete' AS STATUS;

SELECT 'CUSTOMER_RAW' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW_DEV.CRM.CUSTOMER_RAW
UNION ALL
SELECT 'PRODUCT_RAW', COUNT(*) FROM RAW_DEV.CRM.PRODUCT_RAW
UNION ALL
SELECT 'ORDER_RAW', COUNT(*) FROM RAW_DEV.CRM.ORDER_RAW
UNION ALL
SELECT 'EMPLOYEE_RAW', COUNT(*) FROM RAW_DEV.HR.EMPLOYEE_RAW;
