-- ============================================================================
-- CURATED LAYER - Metadata-Driven Dynamic Tables
-- ============================================================================
-- 
-- This script uses a metadata-driven approach to build curated layers:
--   1. CURATED_CONFIG table stores all table/column mappings
--   2. BUILD_CURATED_LAYER procedure reads config and creates dynamic tables
--   3. Adding new tables = inserting rows, not editing SQL
--
-- Schema Structure (one schema per source system):
--   CURATED_DEV.SHARED      - Shared dimensions (DIM_DATE) + Config
--   CURATED_DEV.SAP         - SAP dimensions and facts
--   CURATED_DEV.SALESFORCE  - Salesforce dimensions and facts
--   CURATED_DEV.ORACLE      - Oracle EBS dimensions and facts
--   CURATED_DEV.FHIR        - FHIR dimensions and facts
--   CURATED_DEV.WORKDAY     - Workday dimensions and facts
--   CURATED_DEV.SERVICENOW  - ServiceNow dimensions and facts
--
-- RUN AS: DATA_ADMIN
-- ============================================================================

USE ROLE DATA_ADMIN;
USE DATABASE CURATED_DEV;
USE WAREHOUSE TRANSFORM_WH;

-- ═══════════════════════════════════════════════════════════════════════════
-- CREATE SOURCE SYSTEM SCHEMAS
-- ═══════════════════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS CURATED_DEV.SHARED
    COMMENT = 'Shared reference dimensions and configuration';

CREATE SCHEMA IF NOT EXISTS CURATED_DEV.SAP
    COMMENT = 'SAP S/4HANA curated dimensions and facts';

CREATE SCHEMA IF NOT EXISTS CURATED_DEV.SALESFORCE
    COMMENT = 'Salesforce CRM curated dimensions and facts';

CREATE SCHEMA IF NOT EXISTS CURATED_DEV.ORACLE
    COMMENT = 'Oracle EBS curated dimensions and facts';

CREATE SCHEMA IF NOT EXISTS CURATED_DEV.FHIR
    COMMENT = 'FHIR R4 healthcare curated dimensions and facts';

CREATE SCHEMA IF NOT EXISTS CURATED_DEV.WORKDAY
    COMMENT = 'Workday HCM curated dimensions and facts';

CREATE SCHEMA IF NOT EXISTS CURATED_DEV.SERVICENOW
    COMMENT = 'ServiceNow ITSM curated dimensions and facts';

-- ═══════════════════════════════════════════════════════════════════════════
-- SHARED: DIM_DATE (Static Reference Table)
-- ═══════════════════════════════════════════════════════════════════════════

USE SCHEMA CURATED_DEV.SHARED;

CREATE OR REPLACE TABLE DIM_DATE AS
WITH date_spine AS (
    SELECT DATEADD(DAY, SEQ4(), '2015-01-01')::DATE AS DATE_KEY
    FROM TABLE(GENERATOR(ROWCOUNT => 5844))
)
SELECT
    DATE_KEY,
    YEAR(DATE_KEY) AS YEAR,
    QUARTER(DATE_KEY) AS QUARTER,
    MONTH(DATE_KEY) AS MONTH,
    MONTHNAME(DATE_KEY) AS MONTH_NAME,
    WEEK(DATE_KEY) AS WEEK_OF_YEAR,
    DAYOFWEEK(DATE_KEY) AS DAY_OF_WEEK,
    DAYNAME(DATE_KEY) AS DAY_NAME,
    DAYOFMONTH(DATE_KEY) AS DAY_OF_MONTH,
    CASE WHEN MONTH(DATE_KEY) >= 7 THEN YEAR(DATE_KEY) ELSE YEAR(DATE_KEY) - 1 END AS FISCAL_YEAR,
    CEIL(CASE WHEN MONTH(DATE_KEY) >= 7 THEN MONTH(DATE_KEY) - 6 ELSE MONTH(DATE_KEY) + 6 END / 3.0) AS FISCAL_QUARTER,
    CASE WHEN DAYOFWEEK(DATE_KEY) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM date_spine
WHERE DATE_KEY <= '2030-12-31';

-- ═══════════════════════════════════════════════════════════════════════════
-- CURATED CONFIGURATION TABLE
-- ═══════════════════════════════════════════════════════════════════════════
-- This table defines all curated tables and their SELECT statements.
-- To add a new table: INSERT a row with the source system, target table name,
-- source table, SELECT SQL, and metadata.

-- Drop and recreate to ensure clean state
DROP TABLE IF EXISTS CURATED_DEV.SHARED.CURATED_CONFIG;

CREATE TABLE CURATED_DEV.SHARED.CURATED_CONFIG (
    CONFIG_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    SOURCE_SYSTEM VARCHAR(50) NOT NULL,
    TARGET_TABLE VARCHAR(100) NOT NULL,
    TABLE_TYPE VARCHAR(20) NOT NULL DEFAULT 'DIMENSION',  -- DIMENSION or FACT
    SOURCE_TABLE VARCHAR(100) NOT NULL,
    SELECT_SQL VARCHAR(16000) NOT NULL,
    TARGET_LAG VARCHAR(20) DEFAULT '1 hour',
    TABLE_COMMENT VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT UK_CURATED_CONFIG UNIQUE (SOURCE_SYSTEM, TARGET_TABLE)
);

-- ═══════════════════════════════════════════════════════════════════════════
-- SAP S/4HANA CONFIGURATION
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO CURATED_DEV.SHARED.CURATED_CONFIG 
    (SOURCE_SYSTEM, TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT)
VALUES
-- DIM_CUSTOMER
('SAP', 'DIM_CUSTOMER', 'DIMENSION', 'KNA1', '
SELECT
    KUNNR AS CUSTOMER_KEY,
    KUNNR AS CUSTOMER_ID,
    SHA2(KUNNR, 256) AS CUSTOMER_ID_HASH,
    NAME1 AS CUSTOMER_NAME,
    NAME2 AS CUSTOMER_NAME2,
    STRAS AS ADDRESS,
    ORT01 AS CITY,
    PSTLZ AS POSTAL_CODE,
    REGIO AS STATE,
    LAND1 AS COUNTRY,
    TELF1 AS PHONE,
    SMTP_ADDR AS EMAIL,
    BRSCH AS INDUSTRY_CODE,
    KUKLA AS CUSTOMER_CLASS,
    KTOKD AS ACCOUNT_GROUP,
    CASE WHEN LOEVM = ''X'' THEN FALSE ELSE TRUE END AS IS_ACTIVE,
    TRY_TO_DATE(ERDAT::VARCHAR, ''YYYYMMDD'') AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.KNA1
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'SAP Customer Master from KNA1'),

-- DIM_PRODUCT
('SAP', 'DIM_PRODUCT', 'DIMENSION', 'MARA', '
SELECT
    MATNR AS PRODUCT_KEY,
    MATNR AS MATERIAL_NUMBER,
    SHA2(MATNR, 256) AS PRODUCT_ID_HASH,
    MAKTX AS PRODUCT_NAME,
    MTART AS MATERIAL_TYPE,
    MATKL AS MATERIAL_GROUP,
    MBRSH AS INDUSTRY_SECTOR,
    MEINS AS BASE_UOM,
    BRGEW AS GROSS_WEIGHT,
    NTGEW AS NET_WEIGHT,
    GEWEI AS WEIGHT_UNIT,
    CASE WHEN LVORM = ''X'' THEN FALSE ELSE TRUE END AS IS_ACTIVE,
    TRY_TO_DATE(ERSDA::VARCHAR, ''YYYYMMDD'') AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.MARA
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'SAP Material Master from MARA'),

-- DIM_VENDOR
('SAP', 'DIM_VENDOR', 'DIMENSION', 'LFA1', '
SELECT
    LIFNR AS VENDOR_KEY,
    LIFNR AS VENDOR_ID,
    SHA2(LIFNR, 256) AS VENDOR_ID_HASH,
    NAME1 AS VENDOR_NAME,
    NAME2 AS VENDOR_NAME2,
    STRAS AS ADDRESS,
    ORT01 AS CITY,
    PSTLZ AS POSTAL_CODE,
    LAND1 AS COUNTRY,
    TELF1 AS PHONE,
    SMTP_ADDR AS EMAIL,
    CASE WHEN LOEVM = ''X'' THEN FALSE ELSE TRUE END AS IS_ACTIVE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.LFA1
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'SAP Vendor Master from LFA1'),

-- DIM_EMPLOYEE (SAP HR)
('SAP', 'DIM_EMPLOYEE', 'DIMENSION', 'PA0001', '
SELECT
    PERNR AS EMPLOYEE_KEY,
    PERNR AS EMPLOYEE_ID,
    SHA2(PERNR, 256) AS EMPLOYEE_ID_HASH,
    BUKRS AS COMPANY_CODE,
    WERKS AS PERSONNEL_AREA,
    BTRTL AS PERSONNEL_SUBAREA,
    PERSG AS EMPLOYEE_GROUP,
    PERSK AS EMPLOYEE_SUBGROUP,
    ORGEH AS ORG_UNIT,
    STELL AS POSITION,
    PLANS AS JOB,
    KOSTL AS COST_CENTER,
    ABKRS AS PAYROLL_AREA,
    TRY_TO_DATE(BEGDA::VARCHAR, ''YYYYMMDD'') AS VALID_FROM,
    TRY_TO_DATE(ENDDA::VARCHAR, ''YYYYMMDD'') AS VALID_TO,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.PA0001
WHERE "_IS_CURRENT" = TRUE
', '4 hours', 'SAP Employee Org Assignment from PA0001'),

-- FACT_SALES_ORDERS
('SAP', 'FACT_SALES_ORDERS', 'FACT', 'VBAK', '
SELECT
    VBELN AS ORDER_KEY,
    VBELN AS ORDER_NUMBER,
    KUNNR AS CUSTOMER_KEY,
    TRY_TO_DATE(AUDAT::VARCHAR, ''YYYYMMDD'') AS ORDER_DATE,
    TRY_TO_DATE(ERDAT::VARCHAR, ''YYYYMMDD'') AS CREATED_DATE,
    VKORG AS SALES_ORG,
    VTWEG AS DISTRIBUTION_CHANNEL,
    SPART AS DIVISION,
    AUART AS ORDER_TYPE,
    NETWR AS NET_VALUE,
    WAERK AS CURRENCY,
    GBSTK AS ORDER_STATUS,
    CASE WHEN GBSTK = ''C'' THEN TRUE ELSE FALSE END AS IS_COMPLETED,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.VBAK
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'SAP Sales Orders from VBAK'),

-- FACT_SALES_ORDER_ITEMS
('SAP', 'FACT_SALES_ORDER_ITEMS', 'FACT', 'VBAP', '
SELECT
    VBELN || ''-'' || POSNR AS ITEM_KEY,
    VBELN AS ORDER_KEY,
    POSNR AS ITEM_NUMBER,
    MATNR AS PRODUCT_KEY,
    ARKTX AS PRODUCT_DESCRIPTION,
    KWMENG AS ORDER_QUANTITY,
    VRKME AS UNIT_OF_MEASURE,
    NETWR AS NET_VALUE,
    NETPR AS NET_PRICE,
    WAERK AS CURRENCY,
    WERKS AS PLANT,
    LGORT AS STORAGE_LOCATION,
    ABGRU AS REJECTION_REASON,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.VBAP
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'SAP Sales Order Items from VBAP'),

-- FACT_PURCHASE_ORDERS
('SAP', 'FACT_PURCHASE_ORDERS', 'FACT', 'EKKO', '
SELECT
    EBELN AS PO_KEY,
    EBELN AS PO_NUMBER,
    LIFNR AS VENDOR_KEY,
    TRY_TO_DATE(BEDAT::VARCHAR, ''YYYYMMDD'') AS PO_DATE,
    BUKRS AS COMPANY_CODE,
    EKORG AS PURCHASING_ORG,
    EKGRP AS PURCHASING_GROUP,
    BSART AS PO_TYPE,
    BSTYP AS DOC_CATEGORY,
    WAERS AS CURRENCY,
    RLWRT AS TOTAL_VALUE,
    STATU AS STATUS,
    ERNAM AS CREATED_BY,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.EKKO
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'SAP Purchase Orders from EKKO'),

-- FACT_ACCOUNTING_DOCUMENTS
('SAP', 'FACT_ACCOUNTING_DOCUMENTS', 'FACT', 'BKPF', '
SELECT
    BUKRS || ''-'' || BELNR || ''-'' || GJAHR AS DOC_KEY,
    BUKRS AS COMPANY_CODE,
    BELNR AS DOCUMENT_NUMBER,
    GJAHR AS FISCAL_YEAR,
    BLART AS DOCUMENT_TYPE,
    TRY_TO_DATE(BUDAT::VARCHAR, ''YYYYMMDD'') AS POSTING_DATE,
    TRY_TO_DATE(BLDAT::VARCHAR, ''YYYYMMDD'') AS DOCUMENT_DATE,
    MONAT AS FISCAL_PERIOD,
    WAERS AS CURRENCY,
    BSTAT AS DOCUMENT_STATUS,
    USNAM AS CREATED_BY,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SAP.BKPF
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'SAP Accounting Documents from BKPF');

-- ═══════════════════════════════════════════════════════════════════════════
-- SALESFORCE CONFIGURATION
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO CURATED_DEV.SHARED.CURATED_CONFIG 
    (SOURCE_SYSTEM, TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT)
VALUES
-- DIM_ACCOUNT
('SALESFORCE', 'DIM_ACCOUNT', 'DIMENSION', 'ACCOUNT', '
SELECT
    "Id" AS ACCOUNT_KEY,
    "Id" AS ACCOUNT_ID,
    SHA2("Id", 256) AS ACCOUNT_ID_HASH,
    "Name" AS ACCOUNT_NAME,
    "Type" AS ACCOUNT_TYPE,
    "Industry" AS INDUSTRY,
    "AnnualRevenue" AS ANNUAL_REVENUE,
    "NumberOfEmployees" AS EMPLOYEE_COUNT,
    "Rating" AS RATING,
    "BillingStreet" AS BILLING_ADDRESS,
    "BillingCity" AS BILLING_CITY,
    "BillingState" AS BILLING_STATE,
    "BillingPostalCode" AS BILLING_POSTAL_CODE,
    "BillingCountry" AS BILLING_COUNTRY,
    "Phone" AS PHONE,
    "Website" AS WEBSITE,
    "OwnerId" AS OWNER_ID,
    CASE 
        WHEN "AnnualRevenue" >= 100000000 THEN ''ENTERPRISE''
        WHEN "AnnualRevenue" >= 10000000 THEN ''MID-MARKET''
        WHEN "AnnualRevenue" >= 1000000 THEN ''SMB''
        ELSE ''STARTUP''
    END AS ACCOUNT_TIER,
    NOT COALESCE("IsDeleted", FALSE) AS IS_ACTIVE,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.ACCOUNT
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Salesforce Account dimension'),

-- DIM_CONTACT
('SALESFORCE', 'DIM_CONTACT', 'DIMENSION', 'CONTACT', '
SELECT
    "Id" AS CONTACT_KEY,
    "Id" AS CONTACT_ID,
    SHA2("Id", 256) AS CONTACT_ID_HASH,
    "AccountId" AS ACCOUNT_KEY,
    "FirstName" AS FIRST_NAME,
    "LastName" AS LAST_NAME,
    "Email" AS EMAIL,
    "Phone" AS PHONE,
    "Title" AS TITLE,
    "Department" AS DEPARTMENT,
    "MailingCity" AS CITY,
    "MailingState" AS STATE,
    "MailingCountry" AS COUNTRY,
    "LeadSource" AS LEAD_SOURCE,
    NOT COALESCE("IsDeleted", FALSE) AS IS_ACTIVE,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.CONTACT
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Salesforce Contact dimension'),

-- DIM_LEAD
('SALESFORCE', 'DIM_LEAD', 'DIMENSION', 'LEAD', '
SELECT
    "Id" AS LEAD_KEY,
    "Id" AS LEAD_ID,
    SHA2("Id", 256) AS LEAD_ID_HASH,
    "FirstName" AS FIRST_NAME,
    "LastName" AS LAST_NAME,
    "Salutation" AS SALUTATION,
    "Company" AS COMPANY,
    "Email" AS EMAIL,
    "Phone" AS PHONE,
    "MobilePhone" AS MOBILE_PHONE,
    "Title" AS TITLE,
    "Industry" AS INDUSTRY,
    "LeadSource" AS LEAD_SOURCE,
    "Status" AS STATUS,
    "Rating" AS RATING,
    "AnnualRevenue" AS ANNUAL_REVENUE,
    "NumberOfEmployees" AS EMPLOYEE_COUNT,
    "City" AS CITY,
    "State" AS STATE,
    "Country" AS COUNTRY,
    COALESCE("IsConverted", FALSE) AS IS_CONVERTED,
    "ConvertedDate"::DATE AS CONVERTED_DATE,
    "ConvertedAccountId" AS CONVERTED_ACCOUNT_ID,
    "ConvertedContactId" AS CONVERTED_CONTACT_ID,
    "OwnerId" AS OWNER_ID,
    NOT COALESCE("IsDeleted", FALSE) AS IS_ACTIVE,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.LEAD
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Salesforce Lead dimension'),

-- DIM_PRODUCT
('SALESFORCE', 'DIM_PRODUCT', 'DIMENSION', 'PRODUCT2', '
SELECT
    "Id" AS PRODUCT_KEY,
    "Id" AS PRODUCT_ID,
    SHA2("Id", 256) AS PRODUCT_ID_HASH,
    "Name" AS PRODUCT_NAME,
    "ProductCode" AS PRODUCT_CODE,
    "Description" AS DESCRIPTION,
    "Family" AS PRODUCT_FAMILY,
    "QuantityUnitOfMeasure" AS UNIT_OF_MEASURE,
    "StockKeepingUnit" AS SKU,
    COALESCE("IsActive", TRUE) AS IS_ACTIVE,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.PRODUCT2
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'Salesforce Product dimension'),

-- DIM_CAMPAIGN
('SALESFORCE', 'DIM_CAMPAIGN', 'DIMENSION', 'CAMPAIGN', '
SELECT
    "Id" AS CAMPAIGN_KEY,
    "Id" AS CAMPAIGN_ID,
    SHA2("Id", 256) AS CAMPAIGN_ID_HASH,
    "Name" AS CAMPAIGN_NAME,
    "Type" AS CAMPAIGN_TYPE,
    "Status" AS STATUS,
    TRY_TO_DATE("StartDate"::VARCHAR) AS START_DATE,
    TRY_TO_DATE("EndDate"::VARCHAR) AS END_DATE,
    "BudgetedCost" AS BUDGETED_COST,
    "ActualCost" AS ACTUAL_COST,
    "ExpectedRevenue" AS EXPECTED_REVENUE,
    "NumberSent" AS NUMBER_SENT,
    "ExpectedResponse" AS EXPECTED_RESPONSE,
    "OwnerId" AS OWNER_ID,
    COALESCE("IsActive", TRUE) AS IS_ACTIVE,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.CAMPAIGN
WHERE "_IS_CURRENT" = TRUE
', '4 hours', 'Salesforce Campaign dimension'),

-- FACT_OPPORTUNITIES
('SALESFORCE', 'FACT_OPPORTUNITIES', 'FACT', 'OPPORTUNITY', '
SELECT
    "Id" AS OPPORTUNITY_KEY,
    "Id" AS OPPORTUNITY_ID,
    "AccountId" AS ACCOUNT_KEY,
    "OwnerId" AS OWNER_KEY,
    "Name" AS OPPORTUNITY_NAME,
    "Amount" AS AMOUNT,
    TRY_TO_DATE("CloseDate"::VARCHAR) AS CLOSE_DATE,
    "StageName" AS STAGE_NAME,
    "Probability" AS PROBABILITY,
    "Type" AS OPPORTUNITY_TYPE,
    "LeadSource" AS LEAD_SOURCE,
    "ForecastCategory" AS FORECAST_CATEGORY,
    "NextStep" AS NEXT_STEP,
    "FiscalQuarter" AS FISCAL_QUARTER,
    "FiscalYear" AS FISCAL_YEAR,
    COALESCE("IsClosed", FALSE) AS IS_CLOSED,
    COALESCE("IsWon", FALSE) AS IS_WON,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.OPPORTUNITY
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Salesforce Opportunity fact'),

-- FACT_CASES
('SALESFORCE', 'FACT_CASES', 'FACT', 'CASE', '
SELECT
    "Id" AS CASE_KEY,
    "CaseNumber" AS CASE_NUMBER,
    "AccountId" AS ACCOUNT_KEY,
    "ContactId" AS CONTACT_KEY,
    "OwnerId" AS OWNER_KEY,
    "Subject" AS SUBJECT,
    "Description" AS DESCRIPTION,
    "Status" AS STATUS,
    "Priority" AS PRIORITY,
    "Origin" AS ORIGIN,
    "Type" AS CASE_TYPE,
    COALESCE("IsClosed", FALSE) AS IS_CLOSED,
    COALESCE("IsEscalated", FALSE) AS IS_ESCALATED,
    "ClosedDate"::TIMESTAMP_NTZ AS CLOSED_DATE,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.CASE
WHERE "_IS_CURRENT" = TRUE
', '30 minutes', 'Salesforce Case fact'),

-- FACT_TASKS
('SALESFORCE', 'FACT_TASKS', 'FACT', 'TASK', '
SELECT
    "Id" AS TASK_KEY,
    "WhatId" AS RELATED_TO_KEY,
    "WhoId" AS CONTACT_KEY,
    "OwnerId" AS OWNER_KEY,
    "Subject" AS SUBJECT,
    "Status" AS STATUS,
    "Priority" AS PRIORITY,
    "Description" AS DESCRIPTION,
    TRY_TO_DATE("ActivityDate"::VARCHAR) AS ACTIVITY_DATE,
    COALESCE("IsClosed", FALSE) AS IS_CLOSED,
    COALESCE("IsHighPriority", FALSE) AS IS_HIGH_PRIORITY,
    COALESCE("IsRecurrence", FALSE) AS IS_RECURRENCE,
    "CreatedDate"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SALESFORCE.TASK
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Salesforce Task fact');

-- ═══════════════════════════════════════════════════════════════════════════
-- ORACLE EBS CONFIGURATION
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO CURATED_DEV.SHARED.CURATED_CONFIG 
    (SOURCE_SYSTEM, TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT)
VALUES
-- DIM_PARTY (Customer/Vendor)
('ORACLE', 'DIM_PARTY', 'DIMENSION', 'HZ_PARTIES', '
SELECT
    "PARTY_ID" AS PARTY_KEY,
    "PARTY_ID" AS PARTY_ID,
    SHA2("PARTY_ID"::VARCHAR, 256) AS PARTY_ID_HASH,
    "PARTY_NUMBER" AS PARTY_NUMBER,
    "PARTY_NAME" AS PARTY_NAME,
    "PARTY_TYPE" AS PARTY_TYPE,
    "ADDRESS1" AS ADDRESS,
    "ADDRESS2" AS ADDRESS2,
    "CITY" AS CITY,
    "STATE" AS STATE,
    "POSTAL_CODE" AS POSTAL_CODE,
    "COUNTRY" AS COUNTRY,
    "CATEGORY_CODE" AS CATEGORY,
    "SIC_CODE" AS SIC_CODE,
    "DUNS_NUMBER" AS DUNS_NUMBER,
    "STATUS" = ''A'' AS IS_ACTIVE,
    "CREATED_BY" AS CREATED_BY,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.HZ_PARTIES
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Oracle Party/Customer dimension from HZ_PARTIES'),

-- DIM_VENDOR (from AP_SUPPLIERS)
('ORACLE', 'DIM_VENDOR', 'DIMENSION', 'AP_SUPPLIERS', '
SELECT
    "VENDOR_ID" AS VENDOR_KEY,
    "VENDOR_ID" AS VENDOR_ID,
    SHA2("VENDOR_ID"::VARCHAR, 256) AS VENDOR_ID_HASH,
    "VENDOR_NAME" AS VENDOR_NAME,
    "SEGMENT1" AS VENDOR_NUMBER,
    "VENDOR_TYPE_LOOKUP_CODE" AS VENDOR_TYPE,
    "PAYMENT_METHOD_LOOKUP_CODE" AS PAYMENT_METHOD,
    "PAY_GROUP_LOOKUP_CODE" AS PAY_GROUP,
    "PAYMENT_PRIORITY" AS PAYMENT_PRIORITY,
    "ENABLED_FLAG" = ''Y'' AS IS_ACTIVE,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.AP_SUPPLIERS
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'Oracle Vendor/Supplier dimension from AP_SUPPLIERS'),

-- DIM_ITEM (Product/Inventory)
('ORACLE', 'DIM_ITEM', 'DIMENSION', 'MTL_SYSTEM_ITEMS_B', '
SELECT
    "INVENTORY_ITEM_ID" AS ITEM_KEY,
    "INVENTORY_ITEM_ID" AS ITEM_ID,
    SHA2("INVENTORY_ITEM_ID"::VARCHAR, 256) AS ITEM_ID_HASH,
    "SEGMENT1" AS ITEM_NUMBER,
    "DESCRIPTION" AS ITEM_DESCRIPTION,
    "ITEM_TYPE" AS ITEM_TYPE,
    "PRIMARY_UOM_CODE" AS PRIMARY_UOM,
    "INVENTORY_ITEM_FLAG" AS INVENTORY_ITEM_FLAG,
    "STOCK_ENABLED_FLAG" AS STOCK_ENABLED_FLAG,
    "PURCHASING_ENABLED_FLAG" AS PURCHASING_ENABLED,
    "CUSTOMER_ORDER_ENABLED_FLAG" AS ORDER_ENABLED,
    "LIST_PRICE_PER_UNIT" AS LIST_PRICE,
    "UNIT_WEIGHT" AS UNIT_WEIGHT,
    "WEIGHT_UOM_CODE" AS WEIGHT_UOM,
    "ORGANIZATION_ID" AS ORGANIZATION_ID,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.MTL_SYSTEM_ITEMS_B
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'Oracle Item/Product dimension from MTL_SYSTEM_ITEMS_B'),

-- DIM_EMPLOYEE
('ORACLE', 'DIM_EMPLOYEE', 'DIMENSION', 'HR_ALL_PEOPLE_F', '
SELECT
    "PERSON_ID" AS EMPLOYEE_KEY,
    "PERSON_ID" AS PERSON_ID,
    SHA2("PERSON_ID"::VARCHAR, 256) AS PERSON_ID_HASH,
    "EMPLOYEE_NUMBER" AS EMPLOYEE_NUMBER,
    "FIRST_NAME" AS FIRST_NAME,
    "MIDDLE_NAMES" AS MIDDLE_NAME,
    "LAST_NAME" AS LAST_NAME,
    "FULL_NAME" AS FULL_NAME,
    "EMAIL_ADDRESS" AS EMAIL,
    "DATE_OF_BIRTH"::DATE AS DATE_OF_BIRTH,
    "SEX" AS GENDER,
    "MARITAL_STATUS" AS MARITAL_STATUS,
    "BUSINESS_GROUP_ID" AS BUSINESS_GROUP_ID,
    "CURRENT_EMPLOYEE_FLAG" = ''Y'' AS IS_ACTIVE,
    TRY_TO_DATE("EFFECTIVE_START_DATE"::VARCHAR) AS START_DATE,
    TRY_TO_DATE("EFFECTIVE_END_DATE"::VARCHAR) AS END_DATE,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.HR_ALL_PEOPLE_F
WHERE "_IS_CURRENT" = TRUE
', '4 hours', 'Oracle Employee dimension from HR_ALL_PEOPLE_F'),

-- FACT_ORDER_HEADERS
('ORACLE', 'FACT_ORDER_HEADERS', 'FACT', 'OE_ORDER_HEADERS_ALL', '
SELECT
    "HEADER_ID" AS ORDER_KEY,
    "HEADER_ID" AS ORDER_HEADER_ID,
    "ORDER_NUMBER" AS ORDER_NUMBER,
    "SOLD_TO_ORG_ID" AS CUSTOMER_KEY,
    "SHIP_TO_ORG_ID" AS SHIP_TO_KEY,
    "INVOICE_TO_ORG_ID" AS INVOICE_TO_KEY,
    "ORG_ID" AS ORG_ID,
    TRY_TO_TIMESTAMP("ORDERED_DATE"::VARCHAR) AS ORDER_DATE,
    "ORDER_TYPE_ID" AS ORDER_TYPE_ID,
    "TRANSACTIONAL_CURR_CODE" AS CURRENCY,
    "FLOW_STATUS_CODE" AS STATUS,
    "BOOKED_FLAG" = ''Y'' AS IS_BOOKED,
    "FLOW_STATUS_CODE" = ''CANCELLED'' AS IS_CANCELLED,
    "SALESREP_ID" AS SALESREP_ID,
    "PRICE_LIST_ID" AS PRICE_LIST_ID,
    "PAYMENT_TERM_ID" AS PAYMENT_TERM_ID,
    "SHIPPING_METHOD_CODE" AS SHIPPING_METHOD,
    "FREIGHT_TERMS_CODE" AS FREIGHT_TERMS,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.OE_ORDER_HEADERS_ALL
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Oracle Order Headers from OE_ORDER_HEADERS_ALL'),

-- FACT_ORDER_LINES
('ORACLE', 'FACT_ORDER_LINES', 'FACT', 'OE_ORDER_LINES_ALL', '
SELECT
    "LINE_ID" AS LINE_KEY,
    "HEADER_ID" AS ORDER_KEY,
    "LINE_NUMBER" AS LINE_NUMBER,
    "INVENTORY_ITEM_ID" AS ITEM_KEY,
    "ORDERED_ITEM" AS ORDERED_ITEM,
    "ORG_ID" AS ORG_ID,
    "ORDERED_QUANTITY" AS ORDERED_QUANTITY,
    "UNIT_SELLING_PRICE" AS UNIT_PRICE,
    "UNIT_LIST_PRICE" AS LIST_PRICE,
    "ORDERED_QUANTITY" * "UNIT_SELLING_PRICE" AS LINE_AMOUNT,
    "ORDER_QUANTITY_UOM" AS UOM,
    "FLOW_STATUS_CODE" AS STATUS,
    TRY_TO_DATE("SCHEDULE_SHIP_DATE"::VARCHAR) AS SCHEDULED_SHIP_DATE,
    TRY_TO_DATE("ACTUAL_SHIPMENT_DATE"::VARCHAR) AS ACTUAL_SHIP_DATE,
    "CANCELLED_FLAG" = ''Y'' AS IS_CANCELLED,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.OE_ORDER_LINES_ALL
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Oracle Order Lines from OE_ORDER_LINES_ALL'),

-- FACT_AP_INVOICES
('ORACLE', 'FACT_AP_INVOICES', 'FACT', 'AP_INVOICES_ALL', '
SELECT
    "INVOICE_ID" AS INVOICE_KEY,
    "INVOICE_ID" AS INVOICE_ID,
    "INVOICE_NUM" AS INVOICE_NUMBER,
    "VENDOR_ID" AS VENDOR_KEY,
    "VENDOR_SITE_ID" AS VENDOR_SITE_ID,
    "ORG_ID" AS ORG_ID,
    "INVOICE_AMOUNT" AS INVOICE_AMOUNT,
    "INVOICE_CURRENCY_CODE" AS CURRENCY,
    "INVOICE_TYPE_LOOKUP_CODE" AS INVOICE_TYPE,
    "SOURCE" AS SOURCE,
    TRY_TO_DATE("INVOICE_DATE"::VARCHAR) AS INVOICE_DATE,
    TRY_TO_DATE("TERMS_DATE"::VARCHAR) AS TERMS_DATE,
    "PAYMENT_STATUS_FLAG" AS PAYMENT_STATUS,
    "APPROVAL_STATUS" AS APPROVAL_STATUS,
    "CANCELLED_DATE" IS NOT NULL AS IS_CANCELLED,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.AP_INVOICES_ALL
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Oracle AP Invoices from AP_INVOICES_ALL'),

-- FACT_AR_INVOICES (from RA_CUSTOMER_TRX_ALL)
('ORACLE', 'FACT_AR_INVOICES', 'FACT', 'RA_CUSTOMER_TRX_ALL', '
SELECT
    "CUSTOMER_TRX_ID" AS INVOICE_KEY,
    "CUSTOMER_TRX_ID" AS INVOICE_ID,
    "TRX_NUMBER" AS INVOICE_NUMBER,
    "BILL_TO_CUSTOMER_ID" AS CUSTOMER_KEY,
    "SHIP_TO_CUSTOMER_ID" AS SHIP_TO_CUSTOMER_KEY,
    "ORG_ID" AS ORG_ID,
    "INVOICE_CURRENCY_CODE" AS CURRENCY,
    TRY_TO_DATE("TRX_DATE"::VARCHAR) AS INVOICE_DATE,
    "CUST_TRX_TYPE_ID" AS TRANSACTION_TYPE_ID,
    "COMPLETE_FLAG" = ''Y'' AS IS_COMPLETE,
    "STATUS_TRX" AS STATUS,
    "TERM_ID" AS TERM_ID,
    "PRIMARY_SALESREP_ID" AS SALESREP_ID,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.RA_CUSTOMER_TRX_ALL
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Oracle AR Invoices from RA_CUSTOMER_TRX_ALL'),

-- FACT_GL_JOURNAL_LINES
('ORACLE', 'FACT_GL_JOURNAL_LINES', 'FACT', 'GL_JE_LINES', '
SELECT
    "JE_HEADER_ID"::VARCHAR || ''-'' || "JE_LINE_NUM"::VARCHAR AS LINE_KEY,
    "JE_HEADER_ID" AS HEADER_ID,
    "JE_LINE_NUM" AS LINE_NUMBER,
    "LEDGER_ID" AS LEDGER_ID,
    "CODE_COMBINATION_ID" AS ACCOUNT_KEY,
    "PERIOD_NAME" AS PERIOD_NAME,
    "EFFECTIVE_DATE"::DATE AS EFFECTIVE_DATE,
    "ENTERED_DR" AS ENTERED_DEBIT,
    "ENTERED_CR" AS ENTERED_CREDIT,
    "ACCOUNTED_DR" AS ACCOUNTED_DEBIT,
    "ACCOUNTED_CR" AS ACCOUNTED_CREDIT,
    "DESCRIPTION" AS DESCRIPTION,
    "STATUS" AS STATUS,
    "CREATION_DATE"::TIMESTAMP_NTZ AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.ORACLE.GL_JE_LINES
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Oracle GL Journal Lines from GL_JE_LINES');

-- ═══════════════════════════════════════════════════════════════════════════
-- FHIR R4 CONFIGURATION
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO CURATED_DEV.SHARED.CURATED_CONFIG 
    (SOURCE_SYSTEM, TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT)
VALUES
-- DIM_PATIENT
('FHIR', 'DIM_PATIENT', 'DIMENSION', 'PATIENT', '
SELECT
    "id" AS PATIENT_KEY,
    "id" AS PATIENT_ID,
    SHA2("id", 256) AS PATIENT_ID_HASH,
    "name"[0]:given[0]::VARCHAR AS FIRST_NAME,
    "name"[0]:family::VARCHAR AS LAST_NAME,
    "gender" AS GENDER,
    TRY_TO_DATE("birthDate"::VARCHAR) AS BIRTH_DATE,
    "address"[0]:city::VARCHAR AS CITY,
    "address"[0]:state::VARCHAR AS STATE,
    "address"[0]:postalCode::VARCHAR AS POSTAL_CODE,
    "address"[0]:country::VARCHAR AS COUNTRY,
    "telecom"[0]:value::VARCHAR AS PHONE,
    COALESCE("active", TRUE) AS IS_ACTIVE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.PATIENT
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'FHIR Patient dimension'),

-- DIM_PRACTITIONER
('FHIR', 'DIM_PRACTITIONER', 'DIMENSION', 'PRACTITIONER', '
SELECT
    "id" AS PRACTITIONER_KEY,
    "id" AS PRACTITIONER_ID,
    SHA2("id", 256) AS PRACTITIONER_ID_HASH,
    "name"[0]:given[0]::VARCHAR AS FIRST_NAME,
    "name"[0]:family::VARCHAR AS LAST_NAME,
    "name"[0]:prefix[0]::VARCHAR AS PREFIX,
    "gender" AS GENDER,
    "identifier"[0]:value::VARCHAR AS NPI_NUMBER,
    "qualification"[0]:code:coding[0]:code::VARCHAR AS SPECIALTY_CODE,
    "qualification"[0]:code:coding[0]:display::VARCHAR AS SPECIALTY,
    "telecom"[0]:value::VARCHAR AS PHONE,
    "telecom"[1]:value::VARCHAR AS EMAIL,
    COALESCE("active", TRUE) AS IS_ACTIVE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.PRACTITIONER
WHERE "_IS_CURRENT" = TRUE
', '4 hours', 'FHIR Practitioner dimension'),

-- DIM_ORGANIZATION
('FHIR', 'DIM_ORGANIZATION', 'DIMENSION', 'ORGANIZATION', '
SELECT
    "id" AS ORGANIZATION_KEY,
    "id" AS ORGANIZATION_ID,
    SHA2("id", 256) AS ORGANIZATION_ID_HASH,
    "name" AS ORGANIZATION_NAME,
    "type"[0]:coding[0]:display::VARCHAR AS ORGANIZATION_TYPE,
    "address"[0]:city::VARCHAR AS CITY,
    "address"[0]:state::VARCHAR AS STATE,
    "address"[0]:country::VARCHAR AS COUNTRY,
    "telecom"[0]:value::VARCHAR AS PHONE,
    COALESCE("active", TRUE) AS IS_ACTIVE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.ORGANIZATION
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'FHIR Organization dimension'),

-- FACT_ENCOUNTERS
('FHIR', 'FACT_ENCOUNTERS', 'FACT', 'ENCOUNTER', '
SELECT
    "id" AS ENCOUNTER_KEY,
    "id" AS ENCOUNTER_ID,
    REPLACE("subject":reference::VARCHAR, ''Patient/'', '''') AS PATIENT_KEY,
    "class":code::VARCHAR AS ENCOUNTER_CLASS,
    "class":display::VARCHAR AS ENCOUNTER_CLASS_DISPLAY,
    "type"[0]:coding[0]:code::VARCHAR AS ENCOUNTER_TYPE_CODE,
    "type"[0]:coding[0]:display::VARCHAR AS ENCOUNTER_TYPE,
    "status" AS STATUS,
    "reasonCode"[0]:coding[0]:display::VARCHAR AS REASON,
    TRY_TO_TIMESTAMP("period":start::VARCHAR) AS START_TIME,
    TRY_TO_TIMESTAMP("period":end::VARCHAR) AS END_TIME,
    DATEDIFF(''minute'', TRY_TO_TIMESTAMP("period":start::VARCHAR), TRY_TO_TIMESTAMP("period":end::VARCHAR)) AS DURATION_MINUTES,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.ENCOUNTER
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'FHIR Encounter fact'),

-- FACT_CONDITIONS
('FHIR', 'FACT_CONDITIONS', 'FACT', 'CONDITION', '
SELECT
    "id" AS CONDITION_KEY,
    "id" AS CONDITION_ID,
    REPLACE("subject":reference::VARCHAR, ''Patient/'', '''') AS PATIENT_KEY,
    REPLACE("encounter":reference::VARCHAR, ''Encounter/'', '''') AS ENCOUNTER_KEY,
    "code":coding[0]:code::VARCHAR AS CONDITION_CODE,
    "code":coding[0]:display::VARCHAR AS CONDITION_NAME,
    "code":coding[0]:system::VARCHAR AS CODE_SYSTEM,
    "clinicalStatus":coding[0]:code::VARCHAR AS CLINICAL_STATUS,
    "verificationStatus":coding[0]:code::VARCHAR AS VERIFICATION_STATUS,
    "category"[0]:coding[0]:display::VARCHAR AS CATEGORY,
    "severity":coding[0]:display::VARCHAR AS SEVERITY,
    TRY_TO_DATE("onsetDateTime"::VARCHAR) AS ONSET_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.CONDITION
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'FHIR Condition/Diagnosis fact'),

-- FACT_OBSERVATIONS
('FHIR', 'FACT_OBSERVATIONS', 'FACT', 'OBSERVATION', '
SELECT
    "id" AS OBSERVATION_KEY,
    "id" AS OBSERVATION_ID,
    REPLACE("subject":reference::VARCHAR, ''Patient/'', '''') AS PATIENT_KEY,
    "code":coding[0]:code::VARCHAR AS OBSERVATION_CODE,
    "code":coding[0]:display::VARCHAR AS OBSERVATION_NAME,
    "category"[0]:coding[0]:display::VARCHAR AS CATEGORY,
    "status" AS STATUS,
    "valueQuantity":value::NUMBER AS VALUE_NUMERIC,
    "valueQuantity":unit::VARCHAR AS VALUE_UNIT,
    "interpretation"[0]:coding[0]:code::VARCHAR AS INTERPRETATION_CODE,
    "interpretation"[0]:coding[0]:display::VARCHAR AS INTERPRETATION,
    TRY_TO_TIMESTAMP("effectiveDateTime"::VARCHAR) AS EFFECTIVE_TIME,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.OBSERVATION
WHERE "_IS_CURRENT" = TRUE
', '30 minutes', 'FHIR Observation/Vital Signs fact'),

-- FACT_MEDICATION_REQUESTS
('FHIR', 'FACT_MEDICATION_REQUESTS', 'FACT', 'MEDICATIONREQUEST', '
SELECT
    "id" AS MEDICATION_REQUEST_KEY,
    "id" AS MEDICATION_REQUEST_ID,
    REPLACE("subject":reference::VARCHAR, ''Patient/'', '''') AS PATIENT_KEY,
    REPLACE("requester":reference::VARCHAR, ''Practitioner/'', '''') AS PRACTITIONER_KEY,
    "medicationCodeableConcept":coding[0]:code::VARCHAR AS MEDICATION_CODE,
    "medicationCodeableConcept":coding[0]:display::VARCHAR AS MEDICATION_NAME,
    "status" AS STATUS,
    "intent" AS INTENT,
    "dosageInstruction"[0]:text::VARCHAR AS DOSAGE_INSTRUCTION,
    "dosageInstruction"[0]:timing:repeat:frequency::NUMBER AS FREQUENCY,
    "dosageInstruction"[0]:timing:repeat:period::NUMBER AS PERIOD,
    "dosageInstruction"[0]:timing:repeat:periodUnit::VARCHAR AS PERIOD_UNIT,
    "dispenseRequest":numberOfRepeatsAllowed::NUMBER AS REFILLS_ALLOWED,
    "dispenseRequest":quantity:value::NUMBER AS DISPENSE_QUANTITY,
    TRY_TO_TIMESTAMP("authoredOn"::VARCHAR) AS AUTHORED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.MEDICATIONREQUEST
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'FHIR Medication Request/Prescription fact'),

-- FACT_PROCEDURES
('FHIR', 'FACT_PROCEDURES', 'FACT', 'PROCEDURE', '
SELECT
    "id" AS PROCEDURE_KEY,
    "id" AS PROCEDURE_ID,
    REPLACE("subject":reference::VARCHAR, ''Patient/'', '''') AS PATIENT_KEY,
    REPLACE("encounter":reference::VARCHAR, ''Encounter/'', '''') AS ENCOUNTER_KEY,
    "code":coding[0]:code::VARCHAR AS PROCEDURE_CODE,
    "code":coding[0]:display::VARCHAR AS PROCEDURE_NAME,
    "status" AS STATUS,
    TRY_TO_TIMESTAMP("performedDateTime"::VARCHAR) AS PERFORMED_DATE,
    "outcome":coding[0]:display::VARCHAR AS OUTCOME,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.PROCEDURE
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'FHIR Procedure fact'),

-- FACT_CLAIMS
('FHIR', 'FACT_CLAIMS', 'FACT', 'CLAIM', '
SELECT
    "id" AS CLAIM_KEY,
    "id" AS CLAIM_ID,
    REPLACE("patient":reference::VARCHAR, ''Patient/'', '''') AS PATIENT_KEY,
    REPLACE("provider":reference::VARCHAR, ''Organization/'', '''') AS PROVIDER_KEY,
    "type":coding[0]:code::VARCHAR AS CLAIM_TYPE,
    "status" AS STATUS,
    "use" AS CLAIM_USE,
    "total":value::NUMBER AS TOTAL_AMOUNT,
    "total":currency::VARCHAR AS CURRENCY,
    "priority":coding[0]:code::VARCHAR AS PRIORITY,
    TRY_TO_DATE("created"::VARCHAR) AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.FHIR.CLAIM
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'FHIR Claim fact');

-- ═══════════════════════════════════════════════════════════════════════════
-- WORKDAY HCM CONFIGURATION
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO CURATED_DEV.SHARED.CURATED_CONFIG 
    (SOURCE_SYSTEM, TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT)
VALUES
-- DIM_EMPLOYEE
('WORKDAY', 'DIM_EMPLOYEE', 'DIMENSION', 'WORKERS', '
SELECT
    "Worker_ID" AS EMPLOYEE_KEY,
    "Worker_ID" AS EMPLOYEE_ID,
    "Employee_ID" AS EMPLOYEE_NUMBER,
    SHA2("Worker_ID", 256) AS EMPLOYEE_ID_HASH,
    "Legal_First_Name" AS FIRST_NAME,
    "Legal_Last_Name" AS LAST_NAME,
    "Preferred_First_Name" AS PREFERRED_NAME,
    "Email_Work" AS EMAIL,
    "Phone_Work" AS PHONE,
    "Worker_Type" AS WORKER_TYPE,
    "Worker_Sub_Type" AS WORKER_SUB_TYPE,
    "Business_Title" AS JOB_TITLE,
    "Job_Family" AS JOB_FAMILY,
    "Job_Level" AS JOB_LEVEL,
    "Supervisory_Organization_Name" AS DEPARTMENT,
    "Manager_WID" AS MANAGER_ID,
    "Company_Name" AS COMPANY,
    "Cost_Center" AS COST_CENTER,
    "Work_Location" AS WORK_LOCATION,
    "City" AS CITY,
    "State_Province" AS STATE,
    "Country" AS COUNTRY,
    TRY_TO_DATE("Hire_Date"::VARCHAR) AS HIRE_DATE,
    TRY_TO_DATE("Termination_Date"::VARCHAR) AS TERMINATION_DATE,
    "Active_Status" = ''Active'' AS IS_ACTIVE,
    "Time_Type" AS TIME_TYPE,
    "FTE" AS FTE,
    ROUND(DATEDIFF(''day'', TRY_TO_DATE("Hire_Date"::VARCHAR), COALESCE(TRY_TO_DATE("Termination_Date"::VARCHAR), CURRENT_DATE())) / 365.25, 1) AS TENURE_YEARS,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.WORKDAY.WORKERS
WHERE "_IS_CURRENT" = TRUE
', '4 hours', 'Workday Employee dimension from Workers'),

-- DIM_ORGANIZATION
('WORKDAY', 'DIM_ORGANIZATION', 'DIMENSION', 'ORGANIZATIONS', '
SELECT
    "Organization_WID" AS ORGANIZATION_KEY,
    "Organization_Reference_ID" AS ORGANIZATION_ID,
    SHA2("Organization_WID", 256) AS ORGANIZATION_ID_HASH,
    "Organization_Name" AS ORGANIZATION_NAME,
    "Organization_Code" AS ORGANIZATION_CODE,
    "Organization_Type" AS ORGANIZATION_TYPE,
    "Organization_Subtype" AS ORGANIZATION_SUBTYPE,
    "Superior_Organization_WID" AS PARENT_ORGANIZATION_KEY,
    "Manager_WID" AS MANAGER_ID,
    "Location_WID" AS LOCATION_ID,
    "Company_WID" AS COMPANY_ID,
    COALESCE("Is_Active", TRUE) AS IS_ACTIVE,
    TRY_TO_DATE("Effective_Date"::VARCHAR) AS EFFECTIVE_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.WORKDAY.ORGANIZATIONS
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'Workday Organization dimension'),

-- DIM_JOB_PROFILE
('WORKDAY', 'DIM_JOB_PROFILE', 'DIMENSION', 'JOB_PROFILES', '
SELECT
    "Job_Profile_WID" AS JOB_PROFILE_KEY,
    "Job_Profile_Reference_ID" AS JOB_PROFILE_ID,
    SHA2("Job_Profile_WID", 256) AS JOB_PROFILE_ID_HASH,
    "Job_Profile_Name" AS JOB_PROFILE_NAME,
    "Job_Code" AS JOB_CODE,
    "Job_Description" AS JOB_DESCRIPTION,
    "Job_Family_WID" AS JOB_FAMILY_ID,
    "Job_Family_Name" AS JOB_FAMILY,
    "Job_Level" AS JOB_LEVEL,
    "Management_Level" AS MANAGEMENT_LEVEL,
    COALESCE("Is_Critical_Job", FALSE) AS IS_CRITICAL_JOB,
    COALESCE("Is_Active", TRUE) AS IS_ACTIVE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.WORKDAY.JOB_PROFILES
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'Workday Job Profile dimension'),

-- FACT_COMPENSATION
('WORKDAY', 'FACT_COMPENSATION', 'FACT', 'COMPENSATION', '
SELECT
    "Compensation_WID" AS COMPENSATION_KEY,
    "Worker_WID" AS EMPLOYEE_KEY,
    "Compensation_Plan" AS COMPENSATION_PLAN,
    "Base_Pay_Amount" AS BASE_PAY_AMOUNT,
    "Base_Pay_Currency" AS CURRENCY,
    "Base_Pay_Frequency" AS PAY_FREQUENCY,
    "Total_Compensation" AS TOTAL_COMPENSATION,
    "Bonus_Target_Percent" AS BONUS_TARGET_PERCENT,
    "Compensation_Grade_WID" AS COMPENSATION_GRADE_ID,
    "Compensation_Grade" AS COMPENSATION_GRADE,
    "Pay_Range_Minimum" AS PAY_RANGE_MIN,
    "Pay_Range_Maximum" AS PAY_RANGE_MAX,
    "Compa_Ratio" AS COMPA_RATIO,
    TRY_TO_DATE("Effective_Date"::VARCHAR) AS EFFECTIVE_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.WORKDAY.COMPENSATION
WHERE "_IS_CURRENT" = TRUE
', '4 hours', 'Workday Compensation fact'),

-- FACT_TIME_OFF
('WORKDAY', 'FACT_TIME_OFF', 'FACT', 'TIME_OFF', '
SELECT
    "Time_Off_Request_WID" AS TIME_OFF_KEY,
    "Worker_WID" AS EMPLOYEE_KEY,
    "Time_Off_Type" AS TIME_OFF_TYPE,
    TRY_TO_DATE("Start_Date"::VARCHAR) AS START_DATE,
    TRY_TO_DATE("End_Date"::VARCHAR) AS END_DATE,
    "Total_Days" AS TOTAL_DAYS,
    "Total_Hours" AS TOTAL_HOURS,
    "Status" AS STATUS,
    TRY_TO_DATE("Submitted_Date"::VARCHAR) AS SUBMITTED_DATE,
    "Approver_WID" AS APPROVER_ID,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.WORKDAY.TIME_OFF
WHERE "_IS_CURRENT" = TRUE
', '1 hour', 'Workday Time Off fact'),

-- FACT_BENEFITS
('WORKDAY', 'FACT_BENEFITS', 'FACT', 'BENEFIT_ELECTIONS', '
SELECT
    "Benefit_Election_WID" AS BENEFIT_KEY,
    "Worker_WID" AS EMPLOYEE_KEY,
    "Benefit_Plan_Type" AS BENEFIT_PLAN_TYPE,
    "Benefit_Plan_Name" AS BENEFIT_PLAN_NAME,
    "Coverage_Level" AS COVERAGE_LEVEL,
    "Employee_Cost" AS EMPLOYEE_COST,
    "Employer_Cost" AS EMPLOYER_COST,
    TRY_TO_DATE("Election_Date"::VARCHAR) AS ELECTION_DATE,
    TRY_TO_DATE("Coverage_Begin_Date"::VARCHAR) AS COVERAGE_BEGIN_DATE,
    TRY_TO_DATE("Coverage_End_Date"::VARCHAR) AS COVERAGE_END_DATE,
    COALESCE("Is_Active", TRUE) AS IS_ACTIVE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.WORKDAY.BENEFIT_ELECTIONS
WHERE "_IS_CURRENT" = TRUE
', '4 hours', 'Workday Benefits Enrollment fact');

-- ═══════════════════════════════════════════════════════════════════════════
-- SERVICENOW ITSM CONFIGURATION
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO CURATED_DEV.SHARED.CURATED_CONFIG 
    (SOURCE_SYSTEM, TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT)
VALUES
-- DIM_USER
('SERVICENOW', 'DIM_USER', 'DIMENSION', 'SYS_USER', '
SELECT
    "sys_id" AS USER_KEY,
    "sys_id" AS USER_ID,
    SHA2("sys_id", 256) AS USER_ID_HASH,
    "user_name" AS USERNAME,
    "first_name" AS FIRST_NAME,
    "last_name" AS LAST_NAME,
    "name" AS FULL_NAME,
    "email" AS EMAIL,
    "phone" AS PHONE,
    "title" AS JOB_TITLE,
    "department" AS DEPARTMENT,
    "location" AS LOCATION,
    "manager" AS MANAGER_ID,
    "company" AS COMPANY,
    "active" AS IS_ACTIVE,
    "vip" AS IS_VIP,
    "sys_created_on" AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SERVICENOW.SYS_USER
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'ServiceNow User dimension from sys_user'),

-- DIM_CMDB_CI
('SERVICENOW', 'DIM_CMDB_CI', 'DIMENSION', 'CMDB_CI', '
SELECT
    "sys_id" AS CI_KEY,
    "sys_id" AS CI_ID,
    SHA2("sys_id", 256) AS CI_ID_HASH,
    "name" AS CI_NAME,
    "sys_class_name" AS CI_CLASS,
    "short_description" AS DESCRIPTION,
    "manufacturer" AS MANUFACTURER,
    "model_id" AS MODEL_ID,
    "serial_number" AS SERIAL_NUMBER,
    "asset_tag" AS ASSET_TAG,
    "ip_address" AS IP_ADDRESS,
    "mac_address" AS MAC_ADDRESS,
    "install_status" AS INSTALL_STATUS,
    "operational_status" AS OPERATIONAL_STATUS,
    "location" AS LOCATION,
    "department" AS DEPARTMENT,
    "assigned_to" AS ASSIGNED_TO_KEY,
    "vendor" AS VENDOR,
    "cost" AS COST,
    "sys_created_on" AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SERVICENOW.CMDB_CI
WHERE "_IS_CURRENT" = TRUE
', '24 hours', 'ServiceNow CMDB Configuration Item dimension'),

-- FACT_INCIDENTS
('SERVICENOW', 'FACT_INCIDENTS', 'FACT', 'INCIDENT', '
SELECT
    "sys_id" AS INCIDENT_KEY,
    "number" AS INCIDENT_NUMBER,
    "caller_id" AS CALLER_KEY,
    "assigned_to" AS ASSIGNED_TO_KEY,
    "assignment_group" AS ASSIGNMENT_GROUP,
    "short_description" AS SHORT_DESCRIPTION,
    "description" AS DESCRIPTION,
    "priority" AS PRIORITY,
    "urgency" AS URGENCY,
    "impact" AS IMPACT,
    "state" AS STATE,
    "state_display" AS STATE_DISPLAY,
    "category" AS CATEGORY,
    "subcategory" AS SUBCATEGORY,
    "opened_at" AS OPENED_AT,
    "resolved_at" AS RESOLVED_AT,
    "closed_at" AS CLOSED_AT,
    DATEDIFF(''minute'', "opened_at", COALESCE("resolved_at", CURRENT_TIMESTAMP())) AS TIME_TO_RESOLVE_MINUTES,
    "active" AS IS_ACTIVE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SERVICENOW.INCIDENT
WHERE "_IS_CURRENT" = TRUE
', '15 minutes', 'ServiceNow Incident fact'),

-- FACT_CHANGES
('SERVICENOW', 'FACT_CHANGES', 'FACT', 'CHANGE_REQUEST', '
SELECT
    "sys_id" AS CHANGE_KEY,
    "number" AS CHANGE_NUMBER,
    "assigned_to" AS ASSIGNED_TO_KEY,
    "short_description" AS SHORT_DESCRIPTION,
    "description" AS DESCRIPTION,
    "risk" AS RISK,
    "impact" AS IMPACT,
    "state" AS STATE,
    "type" AS CHANGE_TYPE,
    "category" AS CATEGORY,
    "start_date" AS PLANNED_START_DATE,
    "end_date" AS PLANNED_END_DATE,
    "sys_created_on" AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SERVICENOW.CHANGE_REQUEST
WHERE "_IS_CURRENT" = TRUE
', '30 minutes', 'ServiceNow Change Request fact'),

-- FACT_PROBLEMS
('SERVICENOW', 'FACT_PROBLEMS', 'FACT', 'PROBLEM', '
SELECT
    "sys_id" AS PROBLEM_KEY,
    "number" AS PROBLEM_NUMBER,
    "assigned_to" AS ASSIGNED_TO_KEY,
    "assignment_group" AS ASSIGNMENT_GROUP,
    "short_description" AS SHORT_DESCRIPTION,
    "priority" AS PRIORITY,
    "urgency" AS URGENCY,
    "impact" AS IMPACT,
    "state" AS STATE,
    "problem_state" AS PROBLEM_STATE,
    "known_error" AS IS_KNOWN_ERROR,
    "opened_at" AS OPENED_AT,
    "resolved_at" AS RESOLVED_AT,
    "closed_at" AS CLOSED_AT,
    "sys_created_on" AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SERVICENOW.PROBLEM
WHERE "_IS_CURRENT" = TRUE
', '30 minutes', 'ServiceNow Problem fact'),

-- FACT_REQUESTS
('SERVICENOW', 'FACT_REQUESTS', 'FACT', 'SC_REQUEST', '
SELECT
    "sys_id" AS REQUEST_KEY,
    "number" AS REQUEST_NUMBER,
    "requested_for" AS REQUESTED_FOR_KEY,
    "opened_by" AS OPENED_BY_KEY,
    "short_description" AS SHORT_DESCRIPTION,
    "request_state" AS STATE,
    "stage" AS STAGE,
    "price" AS PRICE,
    "sys_created_on" AS CREATED_DATE,
    "_LOADED_AT" AS _SOURCE_LOADED_AT,
    "_SOURCE_SYSTEM",
    "_IS_CURRENT"
FROM RAW_DEV.SERVICENOW.SC_REQUEST
WHERE "_IS_CURRENT" = TRUE
', '30 minutes', 'ServiceNow Service Catalog Request fact');

-- ═══════════════════════════════════════════════════════════════════════════
-- BUILD PROCEDURE: Creates all curated objects from configuration
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE CURATED_DEV.SHARED.BUILD_CURATED_LAYER(
    P_SOURCE_SYSTEM VARCHAR
)
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
    var results = [];
    var sourceSystem = P_SOURCE_SYSTEM.toUpperCase();
    var targetSchema = 'CURATED_DEV.' + sourceSystem;
    
    // Get all configurations for this source system
    var configSql = "SELECT TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT " +
                    "FROM CURATED_DEV.SHARED.CURATED_CONFIG " +
                    "WHERE SOURCE_SYSTEM = '" + sourceSystem + "' " +
                    "AND IS_ACTIVE = TRUE " +
                    "ORDER BY TABLE_TYPE DESC, TARGET_TABLE";
    
    try {
        var configStmt = snowflake.createStatement({sqlText: configSql});
        var configResult = configStmt.execute();
        
        var tableCount = 0;
        
        while (configResult.next()) {
            var tableName = configResult.getColumnValue('TARGET_TABLE');
            var tableType = configResult.getColumnValue('TABLE_TYPE');
            var selectSql = configResult.getColumnValue('SELECT_SQL');
            var targetLag = configResult.getColumnValue('TARGET_LAG');
            var comment = configResult.getColumnValue('TABLE_COMMENT') || '';
            
            // Escape single quotes in comment for SQL
            comment = comment.replace(/'/g, "''");
            
            var createSql = "CREATE OR REPLACE DYNAMIC TABLE " + targetSchema + "." + tableName +
                            " TARGET_LAG = '" + targetLag + "'" +
                            " WAREHOUSE = TRANSFORM_WH" +
                            " COMMENT = '" + comment + "'" +
                            " AS " + selectSql;
            
            try {
                snowflake.createStatement({sqlText: createSql}).execute();
                results.push({
                    object: tableName, 
                    status: 'SUCCESS', 
                    type: tableType
                });
                tableCount++;
            } catch (err) {
                results.push({
                    object: tableName, 
                    status: 'ERROR', 
                    type: tableType,
                    message: err.message
                });
            }
        }
        
        if (tableCount === 0 && results.length === 0) {
            return {
                status: 'WARNING',
                message: 'No configurations found for source system: ' + sourceSystem,
                source_system: sourceSystem
            };
        }
        
        var successCount = results.filter(function(r) { return r.status === 'SUCCESS'; }).length;
        var errorCount = results.filter(function(r) { return r.status === 'ERROR'; }).length;
        
        return {
            status: errorCount === 0 ? 'SUCCESS' : (successCount > 0 ? 'PARTIAL' : 'FAILED'),
            source_system: sourceSystem,
            target_schema: targetSchema,
            objects_created: successCount,
            objects_failed: errorCount,
            details: results
        };
        
    } catch (err) {
        return {status: 'ERROR', message: err.message};
    }
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- BUILD ALL: Procedure to build all source systems at once
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE CURATED_DEV.SHARED.BUILD_ALL_CURATED_LAYERS()
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
    var results = [];
    var sourceSystems = ['SAP', 'SALESFORCE', 'ORACLE', 'FHIR', 'WORKDAY', 'SERVICENOW'];
    
    for (var i = 0; i < sourceSystems.length; i++) {
        var system = sourceSystems[i];
        try {
            var callSql = "CALL CURATED_DEV.SHARED.BUILD_CURATED_LAYER('" + system + "')";
            var stmt = snowflake.createStatement({sqlText: callSql});
            var result = stmt.execute();
            result.next();
            var buildResult = result.getColumnValue(1);
            results.push({
                source_system: system,
                result: buildResult
            });
        } catch (err) {
            results.push({
                source_system: system,
                result: {status: 'ERROR', message: err.message}
            });
        }
    }
    
    var totalSuccess = 0;
    var totalFailed = 0;
    
    for (var j = 0; j < results.length; j++) {
        if (results[j].result && results[j].result.objects_created) {
            totalSuccess += results[j].result.objects_created;
        }
        if (results[j].result && results[j].result.objects_failed) {
            totalFailed += results[j].result.objects_failed;
        }
    }
    
    return {
        status: totalFailed === 0 ? 'SUCCESS' : 'PARTIAL',
        total_objects_created: totalSuccess,
        total_objects_failed: totalFailed,
        systems: results
    };
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- HELPER: View configuration status
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW CURATED_DEV.SHARED.V_CURATED_CONFIG_SUMMARY AS
SELECT 
    SOURCE_SYSTEM,
    TABLE_TYPE,
    COUNT(*) AS TABLE_COUNT,
    SUM(CASE WHEN IS_ACTIVE THEN 1 ELSE 0 END) AS ACTIVE_COUNT
FROM CURATED_DEV.SHARED.CURATED_CONFIG
GROUP BY SOURCE_SYSTEM, TABLE_TYPE
ORDER BY SOURCE_SYSTEM, TABLE_TYPE;

-- ═══════════════════════════════════════════════════════════════════════════
-- GRANTS
-- ═══════════════════════════════════════════════════════════════════════════

-- Grant schema usage
GRANT USAGE ON SCHEMA CURATED_DEV.SHARED TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA CURATED_DEV.SAP TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA CURATED_DEV.SALESFORCE TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA CURATED_DEV.ORACLE TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA CURATED_DEV.FHIR TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA CURATED_DEV.WORKDAY TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA CURATED_DEV.SERVICENOW TO ROLE DATA_ENGINEER;

-- Grant select on config table and view
GRANT SELECT ON TABLE CURATED_DEV.SHARED.CURATED_CONFIG TO ROLE DATA_ENGINEER;
GRANT SELECT ON TABLE CURATED_DEV.SHARED.DIM_DATE TO ROLE DATA_ENGINEER;
GRANT SELECT ON VIEW CURATED_DEV.SHARED.V_CURATED_CONFIG_SUMMARY TO ROLE DATA_ENGINEER;

-- Grant select on all dynamic tables (current and future)
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CURATED_DEV.SAP TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CURATED_DEV.SALESFORCE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CURATED_DEV.ORACLE TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CURATED_DEV.FHIR TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CURATED_DEV.WORKDAY TO ROLE DATA_ENGINEER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA CURATED_DEV.SERVICENOW TO ROLE DATA_ENGINEER;

GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CURATED_DEV.SAP TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CURATED_DEV.SALESFORCE TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CURATED_DEV.ORACLE TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CURATED_DEV.FHIR TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CURATED_DEV.WORKDAY TO ROLE DATA_ENGINEER;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CURATED_DEV.SERVICENOW TO ROLE DATA_ENGINEER;

GRANT USAGE ON PROCEDURE CURATED_DEV.SHARED.BUILD_CURATED_LAYER(VARCHAR) TO ROLE DATA_ENGINEER;
GRANT USAGE ON PROCEDURE CURATED_DEV.SHARED.BUILD_ALL_CURATED_LAYERS() TO ROLE DATA_ENGINEER;

-- ═══════════════════════════════════════════════════════════════════════════
-- USAGE INSTRUCTIONS
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- View configuration summary:
--   SELECT * FROM CURATED_DEV.SHARED.V_CURATED_CONFIG_SUMMARY;
--
-- Build curated layer for a single source system:
--   CALL CURATED_DEV.SHARED.BUILD_CURATED_LAYER('SAP');
--   CALL CURATED_DEV.SHARED.BUILD_CURATED_LAYER('SALESFORCE');
--   CALL CURATED_DEV.SHARED.BUILD_CURATED_LAYER('ORACLE');
--   CALL CURATED_DEV.SHARED.BUILD_CURATED_LAYER('FHIR');
--   CALL CURATED_DEV.SHARED.BUILD_CURATED_LAYER('WORKDAY');
--   CALL CURATED_DEV.SHARED.BUILD_CURATED_LAYER('SERVICENOW');
--
-- Build ALL source systems at once:
--   CALL CURATED_DEV.SHARED.BUILD_ALL_CURATED_LAYERS();
--
-- Add a new table (just insert a row):
--   INSERT INTO CURATED_DEV.SHARED.CURATED_CONFIG 
--     (SOURCE_SYSTEM, TARGET_TABLE, TABLE_TYPE, SOURCE_TABLE, SELECT_SQL, TARGET_LAG, TABLE_COMMENT)
--   VALUES ('SAP', 'DIM_NEW_TABLE', 'DIMENSION', 'SOURCE_TABLE', 'SELECT ...', '1 hour', 'Description');
--
-- Disable a table:
--   UPDATE CURATED_DEV.SHARED.CURATED_CONFIG SET IS_ACTIVE = FALSE WHERE TARGET_TABLE = 'DIM_SOME_TABLE';
--
-- Verify:
--   SHOW DYNAMIC TABLES IN SCHEMA CURATED_DEV.SAP;
--   SELECT * FROM CURATED_DEV.SAP.DIM_CUSTOMER LIMIT 10;
--
-- ═══════════════════════════════════════════════════════════════════════════

SELECT '05_curated_layer.sql completed successfully' AS STATUS;
