-- ============================================================================
-- SNOWFLAKE HORIZON - DYNAMIC GOVERNANCE POLICIES
-- ============================================================================
-- 
-- This script creates dynamic governance controls that:
--   1. Support multiple source systems (SAP, Salesforce, FHIR, Workday, etc.)
--   2. Apply masking based on source system field patterns
--   3. Automatically detect and tag PII columns
--   4. Enable compliance for GDPR, HIPAA, CCPA
--
-- Defense in Depth Strategy:
--   - Layer 1: Role-based access (RBAC)
--   - Layer 2: Column masking (PII protection)
--   - Layer 3: Row access (geographic/department filtering)
--   - Layer 4: Audit trail (built-in)
--
-- RUN AS: DATA_ADMIN
-- ============================================================================

USE ROLE DATA_ADMIN;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE GOVERNANCE;
USE SCHEMA GOVERNANCE.POLICIES;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 1: MASKING POLICIES
-- ═══════════════════════════════════════════════════════════════════════════

-- Standard masking policy for names (works across all source systems)
CREATE OR REPLACE MASKING POLICY MASK_NAME AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'MANAGER', 'ANALYST', 
                                'DATA_STEWARD', 'DATA_ENGINEER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() = 'AI_AGENT' THEN LEFT(val, 1) || '.'
        ELSE '[NAME REDACTED]'
    END;

-- Email masking
CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'MANAGER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('ANALYST', 'DATA_STEWARD') THEN 
            CONCAT(LEFT(val, 2), '***@', SPLIT_PART(val, '@', 2))
        ELSE '[EMAIL REDACTED]'
    END;

-- Phone masking
CREATE OR REPLACE MASKING POLICY MASK_PHONE AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'MANAGER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('ANALYST') THEN 
            'XXX-XXX-' || RIGHT(REGEXP_REPLACE(val, '[^0-9]', ''), 4)
        ELSE '[PHONE REDACTED]'
    END;

-- Address masking
CREATE OR REPLACE MASKING POLICY MASK_ADDRESS AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('MANAGER', 'ANALYST') THEN '[Address in Region]'
        ELSE '[ADDRESS REDACTED]'
    END;

-- SSN/National ID masking
CREATE OR REPLACE MASKING POLICY MASK_SSN AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('MANAGER') THEN 'XXX-XX-' || RIGHT(val, 4)
        ELSE '***-**-****'
    END;

-- Date of Birth masking
CREATE OR REPLACE MASKING POLICY MASK_DOB AS (val DATE)
RETURNS DATE ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('MANAGER', 'ANALYST') THEN DATE_TRUNC('YEAR', val)
        ELSE NULL
    END;

-- Salary/Compensation masking
CREATE OR REPLACE MASKING POLICY MASK_SALARY AS (val NUMBER)
RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('MANAGER') THEN ROUND(val, -4)
        ELSE NULL
    END;

-- Healthcare ID masking (HIPAA)
CREATE OR REPLACE MASKING POLICY MASK_PATIENT_ID AS (val STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'ACCOUNTADMIN') THEN val
        WHEN CURRENT_ROLE() IN ('MANAGER', 'ANALYST') THEN SHA2(val, 256)
        ELSE '[PHI REDACTED]'
    END;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 2: SOURCE SYSTEM PII FIELD MAPPING
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- Maps source system field names to appropriate masking policies
--
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING (
    SOURCE_SYSTEM           VARCHAR(50) NOT NULL,
    SOURCE_TABLE            VARCHAR(100) NOT NULL,
    COLUMN_NAME             VARCHAR(100) NOT NULL,
    PII_TYPE                VARCHAR(50) NOT NULL,  -- NAME, EMAIL, PHONE, ADDRESS, SSN, DOB, SALARY, PATIENT_ID
    MASKING_POLICY          VARCHAR(100) NOT NULL,
    COMPLIANCE_FRAMEWORKS   ARRAY,
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT pk_pii_mapping PRIMARY KEY (SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME)
)
COMMENT = 'Maps source system fields to PII types and masking policies';

-- Insert PII mappings for SAP - KNA1 (Customer Master)
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'KNA1', 'NAME1', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'KNA1', 'NAME2', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'KNA1', 'STRAS', 'ADDRESS', 'MASK_ADDRESS', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'KNA1', 'TELF1', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'KNA1', 'SMTP_ADDR', 'EMAIL', 'MASK_EMAIL', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'KNA1', 'STCEG', 'SSN', 'MASK_SSN', ARRAY_CONSTRUCT('GDPR');

-- SAP PA0002 (HR Personal Data)
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'PA0002', 'VORNA', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'PA0002', 'NACHN', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'PA0002', 'GBDAT', 'DOB', 'MASK_DOB', ARRAY_CONSTRUCT('GDPR');

-- SAP LFA1 (Vendor Master)
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'LFA1', 'NAME1', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'LFA1', 'STRAS', 'ADDRESS', 'MASK_ADDRESS', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SAP', 'LFA1', 'TELF1', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('GDPR', 'CCPA');

-- Insert PII mappings for Salesforce - Account
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'ACCOUNT', 'Name', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'ACCOUNT', 'Phone', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'ACCOUNT', 'BillingStreet', 'ADDRESS', 'MASK_ADDRESS', ARRAY_CONSTRUCT('CCPA');

-- Salesforce Contact
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'CONTACT', 'FirstName', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'CONTACT', 'LastName', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'CONTACT', 'Email', 'EMAIL', 'MASK_EMAIL', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'CONTACT', 'Phone', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'CONTACT', 'MailingStreet', 'ADDRESS', 'MASK_ADDRESS', ARRAY_CONSTRUCT('GDPR', 'CCPA');

-- Salesforce Lead
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'LEAD', 'FirstName', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'LEAD', 'LastName', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SALESFORCE', 'LEAD', 'Email', 'EMAIL', 'MASK_EMAIL', ARRAY_CONSTRUCT('GDPR', 'CCPA');

-- Insert PII mappings for FHIR - Patient
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'FHIR', 'PATIENT', 'id', 'PATIENT_ID', 'MASK_PATIENT_ID', ARRAY_CONSTRUCT('HIPAA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'FHIR', 'PATIENT', 'name', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('HIPAA', 'GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'FHIR', 'PATIENT', 'birthDate', 'DOB', 'MASK_DOB', ARRAY_CONSTRUCT('HIPAA', 'GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'FHIR', 'PATIENT', 'telecom', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('HIPAA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'FHIR', 'PATIENT', 'address', 'ADDRESS', 'MASK_ADDRESS', ARRAY_CONSTRUCT('HIPAA');

-- FHIR Practitioner
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'FHIR', 'PRACTITIONER', 'id', 'PATIENT_ID', 'MASK_PATIENT_ID', ARRAY_CONSTRUCT('HIPAA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'FHIR', 'PRACTITIONER', 'name', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('HIPAA');

-- Insert PII mappings for Workday - RAW LAYER (WORKERS table)
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Legal_First_Name', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Legal_Last_Name', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Email_Work', 'EMAIL', 'MASK_EMAIL', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Email_Personal', 'EMAIL', 'MASK_EMAIL', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Phone_Work', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Phone_Personal', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Date_of_Birth', 'DOB', 'MASK_DOB', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'National_ID', 'SSN', 'MASK_SSN', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'WORKERS', 'Home_Address', 'ADDRESS', 'MASK_ADDRESS', ARRAY_CONSTRUCT('GDPR');

-- Workday - CURATED LAYER (DIM_EMPLOYEE) 
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'DIM_EMPLOYEE', 'FIRST_NAME', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'DIM_EMPLOYEE', 'LAST_NAME', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'DIM_EMPLOYEE', 'EMAIL', 'EMAIL', 'MASK_EMAIL', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'DIM_EMPLOYEE', 'PHONE', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'DIM_EMPLOYEE', 'DATE_OF_BIRTH', 'DOB', 'MASK_DOB', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'DIM_EMPLOYEE', 'NATIONAL_ID', 'SSN', 'MASK_SSN', ARRAY_CONSTRUCT('GDPR', 'CCPA');

-- Workday - Compensation
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'COMPENSATION', 'Total_Base_Pay', 'SALARY', 'MASK_SALARY', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'FACT_COMPENSATION', 'BASE_PAY', 'SALARY', 'MASK_SALARY', ARRAY_CONSTRUCT('GDPR');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'WORKDAY', 'FACT_COMPENSATION', 'TOTAL_COMPENSATION', 'SALARY', 'MASK_SALARY', ARRAY_CONSTRUCT('GDPR');

-- Insert PII mappings for ServiceNow
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SERVICENOW', 'SYS_USER', 'first_name', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SERVICENOW', 'SYS_USER', 'last_name', 'NAME', 'MASK_NAME', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SERVICENOW', 'SYS_USER', 'email', 'EMAIL', 'MASK_EMAIL', ARRAY_CONSTRUCT('GDPR', 'CCPA');
INSERT INTO GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING 
(SOURCE_SYSTEM, SOURCE_TABLE, COLUMN_NAME, PII_TYPE, MASKING_POLICY, COMPLIANCE_FRAMEWORKS)
SELECT 'SERVICENOW', 'SYS_USER', 'phone', 'PHONE', 'MASK_PHONE', ARRAY_CONSTRUCT('GDPR', 'CCPA');

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 3: DYNAMIC MASKING APPLICATION PROCEDURE
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE GOVERNANCE.POLICIES.APPLY_MASKING_FOR_SOURCE_SYSTEM(
    p_source_system VARCHAR,
    p_database VARCHAR,          -- RAW_DEV or CURATED_DEV
    p_table_name VARCHAR
)
RETURNS TABLE (column_name VARCHAR, policy_applied VARCHAR, status VARCHAR)
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_full_table VARCHAR;
    v_schema VARCHAR;
    v_apply_sql VARCHAR;
    result RESULTSET;
BEGIN
    -- Determine schema based on source system
    v_schema := UPPER(p_source_system);
    v_full_table := UPPER(p_database) || '.' || v_schema || '.' || UPPER(p_table_name);
    
    CREATE OR REPLACE TEMPORARY TABLE _masking_results (
        column_name VARCHAR,
        policy_applied VARCHAR,
        status VARCHAR
    );
    
    -- Loop through PII mappings for this source/table
    FOR mapping IN (
        SELECT COLUMN_NAME, MASKING_POLICY
        FROM GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING
        WHERE UPPER(SOURCE_SYSTEM) = UPPER(p_source_system)
          AND UPPER(SOURCE_TABLE) = UPPER(p_table_name)
    )
    DO
        BEGIN
            v_apply_sql := 'ALTER TABLE ' || v_full_table || 
                          ' MODIFY COLUMN "' || mapping.COLUMN_NAME || 
                          '" SET MASKING POLICY GOVERNANCE.POLICIES.' || mapping.MASKING_POLICY;
            
            EXECUTE IMMEDIATE v_apply_sql;
            INSERT INTO _masking_results VALUES (mapping.COLUMN_NAME, mapping.MASKING_POLICY, 'SUCCESS');
        EXCEPTION
            WHEN OTHER THEN
                INSERT INTO _masking_results VALUES (mapping.COLUMN_NAME, mapping.MASKING_POLICY, 'ERROR: ' || SQLERRM);
        END;
    END FOR;
    
    result := (SELECT * FROM _masking_results);
    RETURN TABLE(result);
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 4: APPLY MASKING TO ALL TABLES FOR A SOURCE SYSTEM
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE GOVERNANCE.POLICIES.APPLY_ALL_MASKING_FOR_SOURCE(
    p_source_system VARCHAR
)
RETURNS TABLE (table_name VARCHAR, columns_masked NUMBER, status VARCHAR)
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    result RESULTSET;
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE _all_masking_results (
        table_name VARCHAR,
        columns_masked NUMBER,
        status VARCHAR
    );
    
    -- Get distinct tables for this source system
    FOR tbl IN (
        SELECT DISTINCT SOURCE_TABLE
        FROM GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING
        WHERE UPPER(SOURCE_SYSTEM) = UPPER(p_source_system)
    )
    DO
        BEGIN
            CALL GOVERNANCE.POLICIES.APPLY_MASKING_FOR_SOURCE_SYSTEM(p_source_system, 'RAW_DEV', tbl.SOURCE_TABLE);
            
            LET col_count NUMBER;
            SELECT COUNT(*) INTO col_count
            FROM GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING
            WHERE UPPER(SOURCE_SYSTEM) = UPPER(p_source_system)
              AND UPPER(SOURCE_TABLE) = UPPER(tbl.SOURCE_TABLE);
            
            INSERT INTO _all_masking_results VALUES (tbl.SOURCE_TABLE, col_count, 'SUCCESS');
        EXCEPTION
            WHEN OTHER THEN
                INSERT INTO _all_masking_results VALUES (tbl.SOURCE_TABLE, 0, 'ERROR: ' || SQLERRM);
        END;
    END FOR;
    
    result := (SELECT * FROM _all_masking_results);
    RETURN TABLE(result);
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 5: ROW ACCESS POLICIES
-- ═══════════════════════════════════════════════════════════════════════════

-- Region-based access (GDPR compliance)
CREATE OR REPLACE ROW ACCESS POLICY ROW_ACCESS_BY_REGION
AS (data_region STRING)
RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('DATA_ADMIN', 'PII_VIEWER', 'ACCOUNTADMIN', 'DATA_STEWARD')
    OR data_region IS NULL
    OR data_region NOT IN ('EU', 'UK', 'EMEA')
    OR (data_region IN ('EU', 'UK', 'EMEA') AND CURRENT_ROLE() NOT IN ('EXTERNAL_PARTNER'));

-- Active records only for business users
CREATE OR REPLACE ROW ACCESS POLICY ROW_ACCESS_ACTIVE_ONLY
AS (is_current BOOLEAN)
RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('DATA_ADMIN', 'DATA_ENGINEER', 'DATA_STEWARD', 'ACCOUNTADMIN')
    OR is_current = TRUE;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 6: COMPLIANCE REPORTING VIEW
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW GOVERNANCE.POLICIES.VW_PII_COMPLIANCE_SUMMARY AS
SELECT 
    SOURCE_SYSTEM,
    SOURCE_TABLE,
    COUNT(*) AS PII_COLUMNS,
    ARRAY_AGG(DISTINCT PII_TYPE) AS PII_TYPES,
    LISTAGG(DISTINCT f.value::VARCHAR, ', ') WITHIN GROUP (ORDER BY f.value::VARCHAR) AS COMPLIANCE_FRAMEWORKS
FROM GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING m,
     LATERAL FLATTEN(input => m.COMPLIANCE_FRAMEWORKS) f
GROUP BY SOURCE_SYSTEM, SOURCE_TABLE
ORDER BY SOURCE_SYSTEM, SOURCE_TABLE;

-- ═══════════════════════════════════════════════════════════════════════════
-- GRANTS
-- ═══════════════════════════════════════════════════════════════════════════

GRANT USAGE ON SCHEMA GOVERNANCE.POLICIES TO ROLE DATA_STEWARD;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE.POLICIES TO ROLE DATA_STEWARD;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.POLICIES TO ROLE DATA_STEWARD;
GRANT USAGE ON PROCEDURE GOVERNANCE.POLICIES.APPLY_MASKING_FOR_SOURCE_SYSTEM(VARCHAR, VARCHAR, VARCHAR) TO ROLE DATA_STEWARD;
GRANT USAGE ON PROCEDURE GOVERNANCE.POLICIES.APPLY_ALL_MASKING_FOR_SOURCE(VARCHAR) TO ROLE DATA_STEWARD;

GRANT USAGE ON SCHEMA GOVERNANCE.POLICIES TO ROLE AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA GOVERNANCE.POLICIES TO ROLE AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA GOVERNANCE.POLICIES TO ROLE AUDITOR;

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 7: APPLY MASKING TO CURATED LAYER
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE GOVERNANCE.POLICIES.APPLY_MASKING_TO_CURATED(
    p_source_system VARCHAR
)
RETURNS TABLE (table_name VARCHAR, column_name VARCHAR, policy VARCHAR, status VARCHAR)
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_full_table VARCHAR;
    v_apply_sql VARCHAR;
    v_table_name VARCHAR;
    v_column_name VARCHAR;
    v_policy VARCHAR;
    result RESULTSET;
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE _curated_masking_results (
        table_name VARCHAR,
        column_name VARCHAR,
        policy VARCHAR,
        status VARCHAR
    );
    
    -- Loop through PII mappings for curated tables (DIM_* and FACT_*)
    FOR mapping IN (
        SELECT SOURCE_TABLE, COLUMN_NAME, MASKING_POLICY
        FROM GOVERNANCE.POLICIES.SOURCE_SYSTEM_PII_MAPPING
        WHERE UPPER(SOURCE_SYSTEM) = UPPER(p_source_system)
          AND (SOURCE_TABLE LIKE 'DIM_%' OR SOURCE_TABLE LIKE 'FACT_%')
    )
    DO
        -- Store values in local variables for use in exception handler
        v_table_name := mapping.SOURCE_TABLE;
        v_column_name := mapping.COLUMN_NAME;
        v_policy := mapping.MASKING_POLICY;
        
        BEGIN
            v_full_table := 'CURATED_DEV.' || UPPER(p_source_system) || '.' || v_table_name;
            v_apply_sql := 'ALTER TABLE ' || v_full_table || 
                          ' MODIFY COLUMN "' || v_column_name || 
                          '" SET MASKING POLICY GOVERNANCE.POLICIES.' || v_policy;
            
            EXECUTE IMMEDIATE v_apply_sql;
            INSERT INTO _curated_masking_results VALUES (v_table_name, v_column_name, v_policy, 'SUCCESS');
        EXCEPTION
            WHEN OTHER THEN
                INSERT INTO _curated_masking_results VALUES (v_table_name, v_column_name, v_policy, 'ERROR: ' || SQLERRM);
        END;
    END FOR;
    
    result := (SELECT * FROM _curated_masking_results);
    RETURN TABLE(result);
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- USAGE INSTRUCTIONS
-- ═══════════════════════════════════════════════════════════════════════════
-- 
-- STEP 1: Apply masking to RAW tables for a source system
--   CALL GOVERNANCE.POLICIES.APPLY_ALL_MASKING_FOR_SOURCE('SAP');
--   CALL GOVERNANCE.POLICIES.APPLY_ALL_MASKING_FOR_SOURCE('SALESFORCE');
--   CALL GOVERNANCE.POLICIES.APPLY_ALL_MASKING_FOR_SOURCE('FHIR');
--   CALL GOVERNANCE.POLICIES.APPLY_ALL_MASKING_FOR_SOURCE('WORKDAY');
--   CALL GOVERNANCE.POLICIES.APPLY_ALL_MASKING_FOR_SOURCE('SERVICENOW');
--
-- STEP 2: Apply masking to CURATED tables
--   CALL GOVERNANCE.POLICIES.APPLY_MASKING_TO_CURATED('SAP');
--   CALL GOVERNANCE.POLICIES.APPLY_MASKING_TO_CURATED('SALESFORCE');
--   CALL GOVERNANCE.POLICIES.APPLY_MASKING_TO_CURATED('FHIR');
--   CALL GOVERNANCE.POLICIES.APPLY_MASKING_TO_CURATED('WORKDAY');
--   CALL GOVERNANCE.POLICIES.APPLY_MASKING_TO_CURATED('SERVICENOW');
--
-- APPLY TO SPECIFIC TABLE:
--   CALL GOVERNANCE.POLICIES.APPLY_MASKING_FOR_SOURCE_SYSTEM('WORKDAY', 'CURATED_DEV', 'DIM_EMPLOYEE');
--
-- VIEW COMPLIANCE:
--   SELECT * FROM GOVERNANCE.POLICIES.VW_PII_COMPLIANCE_SUMMARY;
--
-- ═══════════════════════════════════════════════════════════════════════════

SELECT '✓ Governance Policies Created' AS STATUS;
SHOW MASKING POLICIES IN SCHEMA GOVERNANCE.POLICIES;
